-- GFit — base de alimentos.
-- Gerado por scripts/extract_excel.py a partir de FG_Planilha.xlsx.

-- Valores por 100 g.
insert into gfit.foods (name, protein_g, fat_g, carb_g) values
  ('Frango grelhado',32,2.5,0),
  ('Frango cozido',24,2,0),
  ('lula cozida',15.6,0.9,0),
  ('lula grelhada',32.5,1.6,0),
  ('Atum ao natural',19,0.5,0.5),
  ('Peixe magro cozido',20.1,0.9,0),
  ('whey',75,6.5,6.5),
  ('camaroes cozidos',22.4,1,0.4),
  ('claras de ovo',10,0,0.7),
  ('seitan',22.1,1.6,3.5),
  ('nacos soja cru',47,1.3,17.9),
  ('skyr',11,0.2,4),
  ('tremoço',15.6,2.9,9.9),
  ('queijo quark magro',12,0.3,3.9),
  ('queijo fresco magro',12,1,8.5),
  ('leite magro',3.1,0.1,4.5),
  ('feijao',7.2,0.5,13),
  ('Salmão cozido',25.4,8.1,0),
  ('lombo porco grelhado',29.1,8.1,0),
  ('Vaca magra grelhada',27.3,8.2,0),
  ('queijo quark',10,4.3,3.8),
  ('grao',5.8,2.3,14),
  ('tofu',14.2,7,1.6),
  ('costeleta porco grelhado',18.1,14.4,0),
  ('Dourada grelhada',22.3,9.8,0),
  ('Salmão grelhado',24,7.6,0.5),
  ('queijo fresco',6.7,23.9,3.2),
  ('leite meio gordo',3.4,1.6,4.9),
  ('Vaca meio gorda grelhada',24,19.3,0),
  ('queijo fatiado',24,21,1),
  ('Manteiga amendoim',30,52,7.5),
  ('arroz cozido',2.5,0.2,28),
  ('batata cozida',0.6,0.1,18.4),
  ('batata assada',1,0,28.3),
  ('massa cozida',5.2,1.1,24.9),
  ('aveia',14.3,7.3,56.7),
  ('pão',6.8,0.4,59.8),
  ('frutos vermelhos',1.3,0.7,10),
  ('melao/melancia',0.6,0.4,5.7),
  ('uvas/manga',0.7,0.2,18.1),
  ('milho doce',2.6,1.4,14),
  ('granola',16.2,17.8,75.3),
  ('chocapic/estrelitas',8.6,4.6,73.3),
  ('cereais fibra',14,3,40),
  ('figos',0.8,0.3,19),
  ('ananas',0.5,0.1,12.6),
  ('bolacha milho/arroz',6.7,1.7,83.3),
  ('azeite',0.1,99.9,0),
  ('Noz',20,54,21),
  ('amendoa',22.5,56.3,4.1),
  ('amendoim',26,49,16),
  ('girasol',21,51,20),
  ('Linhaça',13.3,40,26.6),
  ('muesli',7.1,14,68.9),
  ('paio',20,3,1),
  ('pudim proteico',10,1.6,6.9),
  ('iogurte natural grego',3.7,10.4,3.7),
  ('dextrose',0,0,92),
  ('Abacate Abóbora cristalizada Abóbora crua Abrótea cozida Abrótea crua Açafrão Açafrão-da-índia seco Acelga crua Açorda Açorda à alentejana Açorda de bacalhau Açorda de marisco Açorda de ovo Açúcar amarelo Açúcar branco Agrião cru Água mineral natural gaseificada, "Água Castello" Água mineral natural gaseificada, "Vimeiro" Água mineral natural gasocarbónica, "Pedras Salgadas" Água mineral natural, "Luso" Aguardente Água, rede pública de abastecimento (Lisboa) Aipo cru Alcachofra cozida Alcachofra crua Alcaparras (picles) Alecrim fresco Alecrim, seco Alface Alface roxa Alheira cozida sem adição de sal Alheira crua Alheira grelhada sem adição de sal Alho cru Alho em pó Alho-francês cru Almôndegas de porco Almôndegas de vaca Almôndegas de vaca e porco Amêijoa aberta ao natural sem sal Amêijoa crua Amêijoas à Bulhão Pato Ameixa branca Ameixa, conserva em calda de açúcar Ameixa encarnada Ameixa rainha Cláudia Ameixa seca Amêndoa, miolo, com pele Amêndoa, miolo, torrada, sem pele Amendoim, miolo Amendoim, miolo, torrado com sal Amendoim, miolo, torrado sem sal Amora Ananás Ananás, conserva em calda de açúcar Ananás desidratado Anchova, conserva em óleo, escorrido Anona Anona desidratada Arroz agulha cru Arroz à valenciana Arroz carolino branqueado cru Arroz cozido simples Arroz de bacalhau Arroz de bacalhau com margarina Arroz de cabidela Arroz de cenoura Arroz de cenoura com azeite Arroz de ervilhas Arroz de feijão Arroz de frango Arroz de frango com feijão e chouriço Arroz de frango malandrinho à moda de Monção Arroz de gambas Arroz de lulas Arroz de manteiga Arroz de marisco Arroz de pato Arroz de peixe Arroz de peixe com ervilhas Arroz de polvo com azeite Arroz de polvo com tomate Arroz de polvo com tomate e vinho Arroz de tamboril Arroz de tamboril malandrinho Arroz de tomate com azeite Arroz de tomate com margarina Arroz de tomate malandrinho Arroz doce Arroz integral cru Atum conserva em óleo Atum de cebolada Atum fresco cru Atum fresco grelhado Avelã, miolo Azeite (4 marcas) Azeitona Bacalhau à Brás Bacalhau à Brás com azeite Bacalhau à Brás com azeite e azeitonas Bacalhau à Gomes de Sá Bacalhau à Gomes de Sá, com azeite Bacalhau assado no forno com azeite Bacalhau com natas Bacalhau com natas, com queijo ralado Bacalhau cozido Bacalhau fresco cozido Bacalhau fresco cru Bacalhau grelhado Bacalhau seco e salgado, demolhado cru Baço de porco Bacon Bacon, grelhado sem adição de sal Bagas goji secas Banana Banha de porco Base em pó para bebida de ananás Base em pó para bebida de laranja Batata assada com pele, sem sal (só a polpa) Batata assada no forno Batata cozida Batata crua Batata doce assada Batata doce crua Batata estufada com cebola, azeite e óleo alimentar Batata, fécula Batata frita caseira (em palitos) Batata frita, de pacote (em rodelas) Bebida à base de soja com açúcar, com cálcio, sal e aromas Bebida à base de soja com açúcar, sal e aromas Bebida à base de soja natural, sem açúcar e sem sal Bebida refrigerante, cola Bebida refrigerante, cola sem açúcar Bebida refrigerante, gasosa Bebida refrigerante, laranja Beldroega crua Berbigão aberto ao natural sem sal Berbigão cru Beringela crua Beringela grelhada com azeite Besugo cru Beterraba (raiz) cozida sem sal Beterraba (raiz) crua Bife de atum fresco, estufado com azeite e vinho Bife de cavalo, alcatra crua Bife de cavalo, alcatra frita com manteiga Bife de cavalo, alcatra frita com margarina Bife de cavalo, alcatra frita, sem molho Bife de espadarte, estufado com azeite e vinho Bife de porco grelhado Bife de vaca à café Bife de vaca à Marrare com manteiga Bife de vaca à Marrare com margarina Bife de vaca com ovo a cavalo com banha Bife de vaca com ovo a cavalo com manteiga Bife de vaca (valor médio de acém, alcatra e lombo) cru Bife de vaca (valor médio de acém, alcatra e lombo) frito com manteiga Bife de vaca (valor médio de acém, alcatra e lombo) frito, sem molho Bife de vaca (valor médio de acém, alcatra e lombo) grelhado Bife de vitela cru Bife de vitela frito Biscoitos, argolas Biscoitos caseiros Biscoitos limão Biscoitos, línguas de gato Biscoitos, línguas de veado Biscoitos, palitos la Reine Bolacha água e sal Bolacha aveia Bolacha "Belga" Bolacha chocolate Bolacha "Cream cracker" Bolacha integral (trigo) Bolacha manteiga Bolacha Maria Bolacha torrada Bolacha "waffer" baunilha Bola de Berlim sem creme Bolo de arroz Bolo de bolacha Maria Bolo de chocolate Bolo de coco Bolo ferradura Bolo inglês Bolo-Rei Brandy Brócolos cozidos Brócolos crus Bulgur Búzio cru Cabeça de porco Cação cru Cação frito Cacau em pó Cachaço de vaca cru Cachucho cru Café, infusão - bica (3 marcas) Café, infusão - café de cafeteira (3 marcas) Café, infusão - carioca (2 marcas) Café, infusão - valor médio (bica 60% e café de cafeteira 40%) Café solúvel em pó com cafeína Café solúvel em pó descafeinado Caldeirada de bacalhau Caldeirada de bacalhau com enchidos e massa Caldeirada de cabrito com azeite e banha Caldeirada de cabrito com azeite e margarina Caldeirada de enguias Caldeirada de enguias à moda de Aveiro Caldeirada de pargo e peixe-espada-preto Caldeirada de peixe Caldeirada de safio com amêijoas Caldeirada de safio com batatas Caldeirada de safio, raia e tamboril Caldo preparado com cubo de carne de galinha (diluição 2%) Caldo preparado com cubo de carne de vaca (diluição 2%) Camarão cozido Camarão cozido sem sal Camarão cru Canela moída Canja de frango com aipo Canja de frango com massa Canónigos crus Cantarilho (Redfish) assado com cebola, tomate, azeite e bacon Cantarilho (Redfish) com batata, no forno Cantarilho (Redfish) cozido Cantarilho (Redfish) cru Cantarilho (Redfish) no forno Caracol cru Carambola Carapau cru Carapau frito Carapau grelhado Cardamomo Caril em pó Carne à bolonhesa Carne à jardineira Carne de porco à alentejana Carne de porco à alentejana sem massa de pimentão Caseína Castanha assada com sal Castanha cozida sem sal Castanha de caju torrada e salgada Castanha de caju torrada, sem sal Castanha do Brasil Castanha, miolo Castanha pilada Cavala cozida Cavala crua Cavala em filetes, conserva em azeite Cavala grelhada Cavala no forno Cebola cozida Cebola crua Cebola frita com óleo alimentar Cebolinho fresco Cenoura baby crua Cenoura cozida Cenoura crua Cereal de pequeno almoço à base de farelo de trigo (tipo "All-Bran") Cereal de pequeno almoço de trigo integral tipo "Weetabix" Cerefólio fresco Cereja (4 variedades) Cereja, conserva em calda de açúcar Cereja, cristalizada Cereja desidratada Cerveja branca Cerveja preta Cerveja sem álcool Chá, infusão, preto Chá, infusão, verde Chambão de vitela cru Chamuça Cherne cozido Cherne cru Cherne grelhado Chicharro cozido Chicharro cru Chicharro grelhado Chicória crua Chispe de porco Choco cru Choco grelhado Chocolate de leite Chocolate em barra, culinária Chocolate em pó Chocolate negro (aproximadamente 50% cacau) Chouriço de carne de porco, cru Chouriço de carne de porco, gordo, cru Chouriço de carne de porco, magro, cozido sem adição de sal Chouriço de carne de porco, magro, cru Chouriço de carne de porco, magro, grelhado sem adição de sal Chouriço de sangue cozido sem adição de sal Chouriço de sangue, cru Chuchu Chucrute Clara de ovo de galinha, crua Clara de ovo de galinha, pasteurizada Clementina Coco seco, ralado Codorniz carne sem pele, crua Codorniz com pele, crua Codorniz com pele, estufada com azeite Codorniz com pele, grelhada Coelho à caçador Coelho cru Coelho em vinha de alhos Coelho estufado Coelho estufado com azeite Coelho estufado com margarina Coentros crus Cogumelos crus Cogumelos enlatados, escorridos Cogumelos fritos com óleo alimentar Colorau Cominhos Compota de ameixa Compota de ananás Compota de cereja Compota de damasco Compota de laranja Condimento de mostarda Coração de galinha cru Coração de porco, cru Coração de porco, estufado com banha e margarina Coração de vaca, cozido Coração de vaca, cru Coração de vaca, estufado com banha e margarina Coração de vitela, cru Corvina cozida Corvina crua Costeleta de cabrito crua Costeleta de cabrito grelhada Costeleta de carneiro, crua Costeleta de porco gorda crua Costeleta de porco gorda grelhada Costeleta de porco grelhada Costeleta de porco meio gorda crua Costeleta de porco meio gorda estufada Costeleta de porco meio gorda estufada com azeite e banha Costeleta de porco meio gorda estufada com azeite e margarina Costeleta de porco meio gorda estufada com margarina Costeleta de porco meio gorda estufada com óleo alimentar e banha Costeleta de porco meio gorda estufada, sem molho Costeleta de porco meio gorda frita panada Costeleta de porco meio gorda grelhada Costeleta de vitela crua Costeleta de vitela frita com margarina Costeleta de vitela frita panada Costeleta de vitela frita, sem molho Costeleta de vitela grelhada Costeleta ou perna de borrego assada com azeite e margarina Costeleta ou perna de borrego assada com margarina Costeleta ou perna de borrego, assada, sem molho Costeleta ou perna de borrego, cozida Costeleta ou perna de borrego, crua Costeleta ou perna de borrego, estufada com azeite e margarina Costeleta ou perna de borrego, estufada com margarina Costeleta ou perna de borrego, estufada sem molho Costeleta ou perna de borrego frita com margarina, sem molho Costeleta ou perna de borrego, grelhada Costeleta ou perna de carneiro magra frita com margarina, sem molho Couve-branca cozida Couve-branca crua Couve-de-Bruxelas cozida Couve-de-Bruxelas crua Couve-flor cozida Couve-flor crua Couve-galega cozida Couve-galega crua Couve-lombarda cozida Couve-lombarda crua Couve-portuguesa cozida Couve-portuguesa crua Couve-roxa crua Cozido à portuguesa Cozido à portuguesa com grão Cravinho Creme culinário Creme culinário líquido, 65% gordura, com sal Creme de camarão Creme de camarão com natas Creme de ervilhas Creme para barrar de cacau e avelãs (8 marcas) Creme vegetal culinário, 75% gordura, sem sal Creme vegetal para barrar 35% gordura, com fitosteróis Creme vegetal para barrar 37% gordura Creme vegetal para barrar 58% gordura, com cálcio Creme vegetal para barrar 70% gordura, 53% ácidos gordos monoinsaturados Creme vegetal para barrar 70% gordura, com sal Creme vegetal para barrar 72% gordura, 33% ácidos gordos polinsaturados Croissant Croquete Croquete de carne de vaca meio-gorda Cubo de carne de galinha para caldo Cubo de carne de vaca para caldo Curgete crua Curgete frita com óleo alimentar Damasco Damasco, conserva em calda de açúcar Damasco seco Dióspiro Dióspiro desidratado Doce de cereja Doce de damasco Doce de framboesa Doce de ginja Doce de maçã Doce de morango Doce de pêssego Donut Donut recheado com doce de fruta Dourada cozida Dourada crua Dourada grelhada Éclair de chocolate Empada Empadão de atum Empadão de bacalhau Empadão de carne com manteiga Empadão de carne com margarina Empadão de carne guisada Empadão de pescada e camarão Endívia crua Enguia crua Enguia frita Entrecosto de porco cozido Entrecosto de porco cru Entrecosto de porco estufado com azeite e banha Entrecosto de porco estufado com azeite e margarina Entrecosto de porco estufado com margarina Entrecosto de porco estufado com óleo alimentar e banha Entrecosto de porco estufado, sem molho Entrecosto de porco grelhado Ervilhas estufadas Ervilhas, grão, congeladas cozidas Ervilhas, grão, congeladas cruas Ervilhas, grão, frescas cozidas Ervilhas, grão, frescas cruas Ervilhas secas cozidas Ervilhas secas cruas Ervilhas, vagens cozidas Ervilhas, vagens cruas Espadarte cru Espadarte grelhado Espargos cozidos Espargos crus Esparguete cozido Esparguete cru Esparguete estufado com cenoura e azeite Esparguete estufado com cenoura e margarina Espetada de porco grelhada Espetada de vaca grelhada Espinafres crus Estragão fresco Estragão seco Faneca crua Farelo de trigo Farinha de alfarroba Farinha de aveia Farinha de centeio Farinha de centeio tipo 70 Farinha de centeio tipo 85 Farinha de cevada Farinha de espelta Farinha de milho tipo 70 Farinha de pau (mandioca) Farinha de trigo integral Farinha de trigo tipo 150 Farinha de trigo tipo 55 Farinha de trigo (valor médio tipo 150 e tipo 55) Farinha láctea 5 frutos tipo "Cerelac" (com farinha de trigo) Farinha láctea maçãs tipo "Cerelac" (com farinha de trigo) Farinha láctea tipo "Cerelac" (com farinha de trigo) Farinheira cozida sem adição de sal Farinheira crua Favada à portuguesa Favas frescas cozidas Favas frescas cruas Favas secas cozidas (demolhadas) Favas secas cruas Feijão branco cozido (demolhado) Feijão branco cru Feijão frade (feijão miúdo) cozido (demolhado) Feijão frade (feijão miúdo) cru Feijão manteiga cozido (demolhado) Feijão manteiga cru Feijão-verde fresco cozido Feijão-verde fresco cru Feijão vermelho seco Feijoada com carne de porco Feijoada com carne de porco e de vaca Feijoada com enchidos e ovos Feijoa (polpa) Fermento em pó Fermento fresco de padeiro Fermento seco de padeiro Fiambre de aves Fiambre de porco Fiambre, pá Fiambre, peito de frango Fiambre, peito de peru Fiambre, perna Fígado de galinha Fígado de porco, cru Fígado de porco, frito com margarina e banha Fígado de porco, frito, sem molho Fígado de porco, grelhado Fígado de vaca, cru Fígado de vaca, frito, sem molho Fígado de vitela, cru Fígado de vitela, frito com banha e manteiga Fígado de vitela, frito, sem molho Fígado de vitela, grelhado Figo (5 variedades) Figo cristalizado Figo seco Filetes de bacalhau fritos Fisális Flocos de arroz Flocos de aveia Flocos de centeio Flocos de cereais e frutos secos tipo "Muesli" Flocos de cevada Flocos de milho tipo "Corn Flakes" Flocos de trigo Flocos de trigo com figos tipo "Nestum" Flocos de trigo com mel tipo "Nestum" Flocos de trigo e arroz enriquecidos com vitaminas, cálcio e ferro Flocos de trigo integral tipo "All-Bran Flakes" Flor de sal Folhas de rabanete cruas Framboesa Framboesa desidratada Francesinha, com molho Frango (1/4) peito e asa com pele, cozidos Frango (1/4), peito e asa com pele, crus Frango (1/4) peito e asa com pele, estufados com azeite e margarina Frango (1/4) peito e asa com pele, estufados com margarina Frango (1/4) peito e asa com pele, estufados sem molho Frango (1/4) peito e asa com pele, grelhados Frango (1/4) perna com costa e pele, assada sem molho Frango (1/4) perna com costa e pele, cozida Frango (1/4), perna com costa e pele, crua Frango (1/4) perna com costa e pele, estufada com azeite e margarina Frango (1/4) perna com costa e pele, estufada com margarina Frango (1/4) perna com costa e pele, estufada sem molho Frango (1/4), perna com costa e pele, grelhada Frango inteiro com pele, assado sem molho Frango inteiro com pele, cozido Frango inteiro com pele, cru Frango inteiro com pele, estufado com azeite e margarina Frango inteiro com pele, estufado com margarina Frango inteiro com pele, estufado sem molho Frango inteiro com pele, grelhado Frango inteiro sem pele, cozido Frango inteiro sem pele, cru Frango inteiro sem pele, estufado com azeite e margarina Frango inteiro sem pele, estufado com margarina Frango inteiro sem pele, estufado sem molho Frango inteiro sem pele, grelhado Frango, pele crua Funcho fresco Galinha de angola com pele, crua Gamba crua Garoupa cozida Garoupa crua Garoupa grelhada Gelado caseiro com bolachas e natas Gelado caseiro com palitos la Reine Gelado de água (sorvete) Gelado de leite Gelatina desidratada (pó ou folha) Gelatina preparada com ananás em conserva Gelatina preparada com laranja e sumo de laranja Geleia de casca de laranja Gema de ovo de galinha, crua Gema de ovo de galinha, pasteurizada Gengibre fresco Gérmen de trigo Ginja Gin - Rum- Whisky Goiaba crua, polpa Goraz assado com cebola, tomate, azeite e óleo alimentar Goraz cozido Goraz cru Goraz grelhado Goraz no forno Grão-de-bico cozido (demolhado) Grão-de-bico cru Grelos de couve cozidos Grelos de couve crus Grelos de nabo cozidos Grelos de nabo crus Gressino Groselha Hambúrguer de feijão manteiga frito com azeite Hambúrguer de feijão manteiga frito com óleo de milho Hambúrguer de peru, frito Hambúrguer de porco, frito, sem molho Hambúrguer de porco, grelhado Hambúrguer de vaca, cru Hambúrguer de vaca, frito Hambúrguer de vaca, grelhado Hortelã fresca Imperador assado com cebola, tomate, azeite e óleo alimentar Imperador cozido Imperador cru Imperador grelhado Inhame cru Iogurte gordo, aromatizado, açucarado Iogurte gordo, com polpa e/ou pedaços de fruta, açucarado Iogurte gordo, com polpa e/ou pedaços de fruta e cereais açucarado Iogurte grego com fruta açucarado Iogurte grego magro natural Iogurte grego natural Iogurte líquido magro, aromatizado, açucarado Iogurte líquido meio gordo, aromatizado, açucarado Iogurte líquido meio gordo, natural, açucarado Iogurte magro, aromatizado, açucarado Iogurte magro, com cereais e edulcorantes Iogurte magro, natural Iogurte magro, natural, com edulcorantes Iogurte meio gordo, aromatizado, açucarado Iogurte meio gordo, com polpa e/ou pedaços de fruta, açucarado Iogurte meio gordo, natural Iogurte meio gordo, natural, açucarado Iogurte sem lactose enriquecido em proteína, magro, aromatizado, com pedaços e/ou polpa de fruta, açucarado Iogurte sem lactose líquido, magro, aromatizado, com polpa de fruta, açucarado Iogurte sem lactose líquido, magro, aromatizado, com polpa de fruta, com edulcorantes Iogurte sem lactose líquido, meio gordo, aromatizado, açucarado Iogurte sem lactose líquido, meio gordo, aromatizado, com polpa de fruta, açucarado Iogurte sem lactose líquido, meio gordo, natural, açucarado Iogurte sem lactose magro, aromatizado, com pedaços e/ou polpa de fruta, com edulcorantes Iogurte sem lactose magro, natural Iogurte sem lactose meio gordo, aromatizado, açucarado Iogurte sem lactose meio gordo, aromatizado, com frutos secos e cereais, açucarado Iogurte sem lactose meio gordo, aromatizado, com pedaços e/ou polpa de fruta, açucarado Iogurte sem lactose meio gordo, natural Iogurte sem lactose meio gordo, natural, açucarado Jarrete de porco Javali cru Jesuíta Lagosta cozida Lagosta crua Lagostim cozido Lagostim cru Lampreia crua Lapas cruas Laranja (3 variedades) Lasanha à bolonhesa Lebre crua Leite condensado Leite creme Leite de cabra cru Leite de coco, enlatado Leite de ovelha cru Leite evaporado Leite fermentado (Bifidus) gordo, natural Leite fermentado (Bifidus) sem lactose enriquecido com fibra, magro, aromatizado, com pedaços e/ou polpa de fruta, com sementes e/ou cereais, com frutos secos e/ou de casca rija, com edulcorantes Leite fermentado (Bifidus) sem lactose, gordo, natural Leite fermentado (Bifidus) sem lactose líquido, meio gordo, aromatizado, com pedaços e/ou polpa de fruta, açucarado Leite fermentado (Bifidus) sem lactose, magro, aromatizado, com pedaços e/ou polpa de fruta e/ou hortícolas, açucarado, com edulcorantes Leite fermentado (Bifidus) sem lactose magro, natural, com edulcorantes Leite gordo especial, pasteurizado Leite gordo, pasteurizado Leite gordo, pó Leite gordo sem lactose, enriquecido com vitaminas A, D, E e B9 (ácido fólico), UHT Leite gordo, UHT Leite humano Leite humano, colostro Leite humano, transição Leite magro de pastagem, UHT Leite magro, pó Leite magro sem lactose, UHT Leite magro, UHT Leite meio gordo aromatizado, UHT Leite meio gordo de pastagem, UHT Leite meio gordo, pó Leite meio gordo sem lactose, UHT Leite meio gordo, UHT Lentilhas secas cozidas (demolhadas) Lentilhas secas cruas Lichia fresca Licor beneditino Licor de anis Licor de ginja Licor simples Lima Limão Língua de porco crua Língua de vaca, crua Língua de vaca, estufada, sem molho Linguado cru Linguado frito Linguado grelhado Linguiça Lombo de porco assado Lombo de porco assado com azeite e margarina Lombo de porco assado com margarina Lombo de porco assado com óleo alimentar e margarina Lombo de porco assado, sem molho Lombo de porco cru Lombo de porco frito Lombo de porco frito com manteiga Lombo de porco frito com margarina Lombo de porco frito panado Lombo de porco grelhado Lombo de vaca magro assado com azeite e margarina Lombo de vaca magro assado com azeite, manteiga e óleo alimentar Lombo de vaca magro assado com margarina Lombo de vaca magro assado com óleo alimentar e margarina Lombo de vaca magro assado, sem molho Lombo de vaca magro cru Lombo de vaca magro no forno, com tomate, cebola, cenoura e alho Lombo de vitela assado com azeite e margarina Lombo de vitela assado com azeite, margarina e óleo alimentar Lombo de vitela assado com margarina e óleo alimentar Lombo de vitela assado, sem molho Lombo de vitela cru Lombo de vitela frito com margarina Lombo de vitela frito, sem molho Lombo de vitela grelhado Lombo ou pá de cavalo assado com azeite e manteiga Lombo ou pá de cavalo assado com margarina Lombo ou pá de cavalo assado, sem molho Lombo ou pá de cavalo cru Lombo ou pá de cavalo frito com manteiga Lombo ou pá de cavalo frito com margarina Lula crua Lula estufada com cebola, tomate e azeite Lula grelhada Maçã assada com açúcar Maçã assada sem açúcar Maçã com casca Maçã cozida com açúcar Maçã cozida sem açúcar Maçã desidratada Maçã (média com e sem casca) Maçã seca Maçã sem casca Madalena Maionese caseira, com ovo e azeite Maionese caseira, com ovo e óleo de soja Malagueta vermelha fresca Mandioca crua Manga Manga desidratada Manjericão fresco Manjericão seco Manjerona seca Manteiga com sal Manteiga sem sal Maracujá Margarina Margarina 3/4, de girassol Margarina culinária para folhados, com sal Margarina industrial para pastelaria, com sal Margarina vegetal culinária, 80% gordura, com sal Margarina vegetal culinária, com alho e sal Marmelada Marmelo Maruca cozida Maruca crua Massa com ovo cozida Massa com ovo crua Massa de pimentão Massa folhada, congelada Massa miúda crua Massa para lasanha cozida Massa para lasanha crua Massa para pizza Massa quebrada para quiche Meia-desfeita de bacalhau Mel Melaço Melancia Melão (3 variedades) Mel de cana Meloa Merengue Mexilhão cozido sem sal Mexilhão cru Milho, amido (pó) Milho doce em conserva Milho, grão seco cru Minarina (meia margarina) Mirtilo Mirtilo desidratado Molho "Béchamel" com manteiga Molho "Béchamel" com margarina Molho branco com caldo de carne de vaca Molho branco com margarina Molho de bife frito com manteiga Molho de carne de vaca assada com azeite e margarina Molho de carne de vaca assada com margarina Molho de carne de vaca estufada com azeite e margarina Molho de carne de vaca estufada com vegetais, azeite e margarina Molho de lombo de porco frito com banha Molho de lombo de porco frito com banha e margarina Molho de lombo de porco frito com margarina Molho de lombo de vaca frito com creme vegetal sem sal Molho de lombo de vaca frito com margarina Molho de mostarda Molho de soja Molho de tomate Molho de tomate, "ketchup" Molho de vinagrete Molho para francesinha Molho verde Morango Morango desidratado Morcela crua Morcela grelhada sem adição de sal Mortadela Mousse de chocolate Múcua (fruto do embondeiro, baobab) Nabiça crua Nabo (raiz) cozido Nabo (raiz) cru Nata maturada pasteurizada 30% gordura Nata para bater pasteurizada 34% gordura Nata pasteurizada 33% gordura Nata pasteurizada 36% gordura Nata pasteurizada para café, 15% gordura Nata UHT 35% gordura Néctar de alperce Néctar de ananás Néctar de laranja Néctar de maçã Néctar de maçã, "light" Néctar de pera Néctar de pêssego Néctar de pêssego, "light" Néctar de "tutti - frutti" Nectarina Nêspera Noz macadâmia Noz, miolo Noz-moscada Noz pecan Óleo alimentar Óleo "Becel" Óleo de amendoim Óleo de coco Óleo de girassol Óleo de linhaça Óleo de palma Óleo de soja Óleos de milho Omelete Omelete com manteiga Omelete com margarina Orégão seco Orelha de porco, crua Ostra, crua Ovas de bacalhau cruas Ovas de pescada cruas Ovo de codorniz, cru Ovo de galinha, cozido Ovo de galinha, escalfado Ovo de galinha, estrelado Ovo de galinha, estrelado com azeite Ovo de galinha, estrelado com manteiga Ovo de galinha, estrelado com margarina Ovo de galinha inteiro, cru Ovo de galinha líquido, pasteurizado Ovo de galinha, mexido com manteiga Ovo de galinha, mexido com margarina Ovo mexido com leite e margarina Pá de carneiro, assada com azeite e margarina Pá de carneiro, assada com margarina Pá de carneiro assada, sem molho Pá de carneiro, cozida Pá de carneiro, crua Pá de carneiro, estufada sem molho Pá de vitela crua Paio de lombo Paio de lombo entremeado Pão de centeio Pão de centeio integral Pão de forma, de trigo com passas Pão de forma, de trigo enriquecido Pão de leite (trigo) Pão de ló Pão de milho Pão de mistura de trigo e centeio Pão de trigo Pão de trigo integral Pão de trigo integral com passas Pão de trigo integral com sementes de sésamo Pão de trigo integral com soja Pão do coração (trigo) Pão pita Pão ralado Papaia Papaia desidratada Pargo legítimo assado com cebola, tomate e azeite Pargo legítimo cozido Pargo legítimo cru Pargo mulato assado com cebola, tomate e azeite Pargo mulato cozido Pargo mulato cru Pasta de fígado de aves (paté), caseira Pasta de fígado de porco (paté) Pastel de bacalhau Pastel de feijão Pastel de nata Pastel folhado Pastilha elástica Pato com pele, assado sem molho Pato com pele, cru Pato sem pele, assado com margarina Pato sem pele, cru Pato sem pele, estufado com margarina Pé de porco, cru Peito de cabrito cru Peito de cabrito estufado com azeite e margarina Peito de cabrito estufado com azeite e óleo alimentar Peito de cabrito estufado com manteiga e óleo alimentar Peito de cabrito estufado com margarina e óleo alimentar Peito de cabrito estufado, sem molho Peito de cabrito grelhado Peito de carneiro gordo, cozido Peito de carneiro gordo, cru Peito de frango com pele, cozido Peito de frango com pele, cru Peito de frango com pele, estufado com azeite e margarina Peito de frango com pele, estufado com margarina Peito de frango com pele, estufado sem molho Peito de frango sem pele, cozido Peito de frango sem pele, cru Peito de frango sem pele, estufado com azeite e margarina Peito de frango sem pele, estufado com margarina Peito de frango sem pele, estufado sem molho Peito de peru com pele, cru Peito de peru com pele, estufado com margarina Peito de peru sem pele, assado com margarina Peito de peru sem pele, cru Peito de peru sem pele, panado Peito de vitela magro cozido Peito de vitela magro cru Peito de vitela magro estufado Peito de vitela magro estufado com azeite e margarina Peito de vitela magro estufado com azeite, margarina e óleo alimentar Peito de vitela magro estufado com margarina e óleo alimentar Peito de vitela magro estufado, sem molho Peixe-espada-branco cru Peixe-espada-branco frito Peixe-espada-branco grelhado Peixe-espada-preto cru Peixe-espada-preto frito Peixe-espada-preto grelhado Peixinhos da horta Pepino cru Pera (5 variedades) Pera conserva em calda de açúcar Pera cozida com açúcar Pera cozida sem açúcar Pera cristalizada Pera desidratada Percebes crus Perdiz crua Perdiz estufada com margarina Perna de borrego no forno Perna de cabrito assada com azeite e margarina Perna de cabrito assada com óleo alimentar e margarina Perna de cabrito assada, sem molho Perna de cabrito crua Perna de carneiro gorda, assada, sem molho Perna de carneiro gorda, crua Perna de carneiro gorda, estufada sem molho Perna de carneiro magra assada com azeite e margarina Perna de carneiro magra assada com margarina Perna de carneiro magra, assada, sem molho Perna de carneiro magra, crua Perna de carneiro magra, estufada com azeite e margarina Perna de carneiro magra, estufada com margarina Perna de carneiro magra, estufada sem molho Perna de frango sem pele, cozida Perna de frango sem pele, crua Perna de frango sem pele, estufada com azeite e margarina Perna de frango sem pele, estufada com margarina Perna de frango sem pele, estufada sem molho Perna de peru com pele, assada com margarina Perna de peru com pele, crua Perna de peru com pele, estufada com margarina Perna de porco gorda assada com azeite e margarina Perna de porco gorda assada com margarina Perna de porco gorda assada com óleo alimentar e margarina Perna de porco gorda assada, sem molho Perna de porco gorda crua Perna de porco gorda grelhada Perna de porco magra assada com azeite e margarina Perna de porco magra assada com margarina Perna de porco magra assada com óleo alimentar e margarina Perna de porco magra assada, sem molho Perna de porco magra crua Perna de porco magra estufada com azeite e banha Perna de porco magra estufada com azeite e margarina Perna de porco magra estufada com margarina Perna de porco magra estufada com óleo alimentar e banha Perna de porco magra estufada, sem molho Perna de porco magra grelhada Peru inteiro com pele, cru Pescada cozida (valor médio) Pescada crua (valor médio) Pescada da África do Sul cozida Pescada da África do Sul crua Pescada da África do Sul frita Pescada do Chile cozida Pescada do Chile crua Pescada do Chile frita Pescada europeia cozida Pescada europeia crua Pescada europeia frita Pescada frita (valor médio) Pêssego (2 variedades) Pêssego, conserva em calda de açúcar Picanha grelhada Picles de pepino Pimenta branca Pimenta moída Pimenta preta Pimento cru Pimento grelhado Pinhão, miolo Pistácio torrado e salgado Pistácio torrado, sem sal Pizza de queijo e tomate Pizza de queijo, tomate e fiambre Pó achocolatado com alto teor de gordura Pó achocolatado com baixo teor de gordura Polvo cozido sem sal Polvo cru Pombo cru Pota crua Preparado fermentado à base de soja (Vegurte) Presunto Proteína texturizada de soja Pudim de leite e ovos Pudim flan caseiro Pudim instantâneo em pó Pudim instantâneo preparado com leite magro Pudim instantâneo preparado com leite meio gordo Pulmões de porco, crus Puré de batata Queijada de queijo fresco Queijada de queijo magro Queijada de requeijão Queijo Brie Queijo Camembert Queijo Cheddar Queijo creme para barrar Queijo creme para barrar, alto teor polinsaturados Queijo da Ilha Queijo de Azeitão Queijo de Évora Queijo Emmental Queijo flamengo Queijo flamengo 30% gordura Queijo flamengo 45% gordura Queijo fresco açucarado com sabor a fruta Queijo fresco de cabra Queijo fresco de ovelha Queijo fresco magro Queijo fresco meio gordo Queijo fundido 40% gordura Queijo Gouda Queijo Gruyere Queijo Mascarpone Queijo Mozzarella fresco Queijo Parmesão Queijo Quark açucarado magro com sabor a fruta Queijo Quark natural magro Queijo Quark natural meio gordo Queijo Raclette Queijo Roquefort Queijo Serpa Queijo Serra da Estrela Queijo Serra da Estrela, velho Queque Quiabo cru Quiche de espinafres Quiche de vegetais Quiche lorraine Quivi, "Kiwi" Quivi, "Kiwi" desidratado Rabanada Rabanete cru Rábano cru Raia crua Rancho com carne de galinha, porco e vaca Rancho com carne de porco Rebentos de alfalfa crus Rebentos de bambu crus Rebentos de soja crus Rebuçados Requeijão Requeijão 13% de proteína Requeijão 8% de proteína Rim de carneiro, cru Rim de carneiro, frito com margarina Rim de porco, cru Rim de porco, frito com margarina Rim de vaca, cru Rissol Rissol de camarão Rissol de carne com manteiga Rissol de carne com margarina Robalo assado com cebola, azeite, banha e manteiga Robalo cozido Robalo cru Robalo grelhado Rojões de carne gorda Rojões de carne magra Romã Rúcula crua Safio cru Sal Salada de alface e tomate temperada com azeite e vinagre Salada de atum Salada de bacalhau com grão Salada russa Salame Salmão cozido Salmão cru Salmão grelhado Salmonete cru Salpicão Salsa fresca Salsa seca Salsicha de soja Salsicha fresca crua Salsicha fresca estufada com couve e azeite Salsicha fresca estufada com legumes e azeite Salsicha tipo Frankfurt Salsicha tipo Frankfurt frita (escorrido o óleo) sem adição de sal Salsicha tipo Frankfurt grelhada sem adição de sal Sangue de porco, cru Sapateira crua Sarda cozida Sarda crua Sarda grelhada Sardinha frita Sardinha gorda crua Sardinha gorda frita Sardinha gorda grelhada Sardinha meio gorda conserva em água, sem espinha e sem pele Sardinha meio gorda conserva em azeite Sardinha meio gorda conserva em azeite (escorrido) Sardinha meio gorda crua Sardinha meio gorda frita Sardinha meio gorda grelhada Seitan Sementes de abóbora Sementes de cânhamo secas Sementes de chia Sementes de coentro Sementes de girassol Sementes de linhaça cruas Sementes de melão Sementes de mostarda Sementes de papoila Sementes de sésamo Sêmola de milho Shortening para pastelaria Shortening para restaurante Sidra (vinho de maçã) Sobremesa à base de soja Soja cozida sem sal Soja, farinha com baixo teor de gordura Soja, grão seco, cru Solha crua Solha frita Solha grelhada Sonhos Sopa à lavrador Sopa, caldo verde Sopa, canja de galinha Sopa, creme de cenoura Sopa de abóbora Sopa de agrião Sopa de agrião com leite Sopa de agrião com requeijão Sopa de carne de porco Sopa de cebola Sopa de cenoura Sopa de couve-branca Sopa de couve-lombarda Sopa de cozido Sopa de ervilhas Sopa de espinafres Sopa de espinafres com ovos Sopa de favas Sopa de feij',1.1,10.5,2.3),
  ('Abacate',0,0.2,72.4),
  ('Abóbora cristalizada',0.3,0.2,1.7),
  ('Abóbora crua',19.4,0.1,0),
  ('Abrótea cozida',17.2,0.1,0),
  ('Abrótea crua',11.4,5.9,61.5),
  ('Açafrão',6.7,7,44.1),
  ('Açafrão-da-índia seco',1.8,0.2,2.7),
  ('Acelga crua',3.3,4,13.1),
  ('Açorda',3.5,3.3,12.3),
  ('Açorda à alentejana',3.4,3.5,5.7),
  ('Açorda de bacalhau',4.5,1.2,5.4),
  ('Açorda de marisco',3.6,4,14),
  ('Açorda de ovo',0,0,97.5),
  ('Açúcar amarelo',0,0,99.3),
  ('Açúcar branco',3.4,0.9,0.4),
  ('Agrião cru',0,0,0),
  ('Água mineral natural gaseificada, "Água Castello"',0,0,0),
  ('Água mineral natural gaseificada, "Vimeiro"',0,0,0),
  ('Água mineral natural gasocarbónica, "Pedras Salgadas"',0,0,0),
  ('Água mineral natural, "Luso"',0,0,0),
  ('Aguardente',0,0,0),
  ('Água, rede pública de abastecimento (Lisboa)',1.1,0.1,1.5),
  ('Aipo cru',3,0.2,5.3),
  ('Alcachofra cozida',3,0.2,6.8),
  ('Alcachofra crua',2.4,0.9,4.9),
  ('Alcaparras (picles)',1.4,4.4,13.5),
  ('Alecrim fresco',4.9,15.2,46.4),
  ('Alecrim, seco',1.8,0.2,0.8),
  ('Alface',1.3,0.2,1.4),
  ('Alface roxa',8.3,14,26.8),
  ('Alheira cozida sem adição de sal',8.3,18.1,27.4),
  ('Alheira crua',8.1,17,28.5),
  ('Alheira grelhada sem adição de sal',3.8,0.6,11.3),
  ('Alho cru',17.6,1.2,52.3),
  ('Alho em pó',1.8,0.3,2.9),
  ('Alho-francês cru',8,8.9,29.2),
  ('Almôndegas de porco',17,17.4,6.4),
  ('Almôndegas de vaca',19.2,16.7,3.8),
  ('Almôndegas de vaca e porco',23.4,1.8,5.2),
  ('Amêijoa aberta ao natural sem sal',11.7,0.9,2.6),
  ('Amêijoa crua',12.8,2.5,3.2),
  ('Amêijoas à Bulhão Pato',0.6,0.2,7.8),
  ('Ameixa branca',0.2,0.2,27.5),
  ('Ameixa, conserva em calda de açúcar',0.8,0.2,7.4),
  ('Ameixa encarnada',0.8,0.1,11.8),
  ('Ameixa rainha Cláudia',2.9,0.3,37.8),
  ('Ameixa seca',21.6,56,7.2),
  ('Amêndoa, miolo, com pele',21.6,56.8,7.1),
  ('Amêndoa, miolo, torrada, sem pele',25.4,47.7,10.1),
  ('Amendoim, miolo',26.2,51.8,6.6),
  ('Amendoim, miolo, torrado com sal',25.6,49.6,9.5),
  ('Amendoim, miolo, torrado sem sal',1.4,0.9,4.5),
  ('Amora',0.5,0.2,9.5),
  ('Ananás',0.2,0.1,23.2),
  ('Ananás, conserva em calda de açúcar',3.8,1.5,72.8),
  ('Ananás desidratado',25.2,10,0),
  ('Anchova, conserva em óleo, escorrido',1.7,0.4,16.8),
  ('Anona',7.2,1.7,71.6),
  ('Anona desidratada',6.7,0.4,78.1),
  ('Arroz agulha cru',7.6,5.3,7.7),
  ('Arroz à valenciana',7.4,0.5,79.6),
  ('Arroz carolino branqueado cru',2.5,0.2,28),
  ('Arroz cozido simples',3.1,1.6,15.3),
  ('Arroz de bacalhau',5.4,2.1,12.2),
  ('Arroz de bacalhau com margarina',9.4,1.9,12.2),
  ('Arroz de cabidela',3.5,2.3,41),
  ('Arroz de cenoura',1.8,4.2,19.9),
  ('Arroz de cenoura com azeite',2.3,0.2,18),
  ('Arroz de ervilhas',3.1,4.4,20.8),
  ('Arroz de feijão',8.4,7.6,25.2),
  ('Arroz de frango',10.9,3.4,8.8),
  ('Arroz de frango com feijão e chouriço',10.5,5.8,9.3),
  ('Arroz de frango malandrinho à moda de Monção',6.9,3.4,8.8),
  ('Arroz de gambas',4.8,2.1,6.7),
  ('Arroz de lulas',3.8,7.7,44.4),
  ('Arroz de manteiga',6.5,1.4,8.2),
  ('Arroz de marisco',10.8,4.2,8.4),
  ('Arroz de pato',7,3.7,15.5),
  ('Arroz de peixe',4.9,0.8,19.8),
  ('Arroz de peixe com ervilhas',10.2,4.6,10.9),
  ('Arroz de polvo com azeite',5.7,7.1,10),
  ('Arroz de polvo com tomate',6.5,3.6,6.9),
  ('Arroz de polvo com tomate e vinho',5.7,3.8,7.1),
  ('Arroz de tamboril',5.9,0.2,10),
  ('Arroz de tamboril malandrinho',2,4.2,20.1),
  ('Arroz de tomate com azeite',2,3.4,20.2),
  ('Arroz de tomate com margarina',1.9,6,16.8),
  ('Arroz de tomate malandrinho',4.4,3.8,45.2),
  ('Arroz doce',8.6,2.5,71.6),
  ('Arroz integral cru',24.3,13,0),
  ('Atum conserva em óleo',9,9,2.6),
  ('Atum de cebolada',24.1,4.9,0),
  ('Atum fresco cru',28.4,5.8,0),
  ('Atum fresco grelhado',14,66.3,6),
  ('Avelã, miolo',0,99.9,0),
  ('Azeite (4 marcas)',1.4,18.5,0),
  ('Azeitona',9.5,10.1,8.3),
  ('Bacalhau à Brás',8.7,14.7,6.5),
  ('Bacalhau à Brás com azeite',8,3.6,6.5),
  ('Bacalhau à Brás com azeite e azeitonas',6.7,6.3,13.1),
  ('Bacalhau à Gomes de Sá',8.6,10.4,7.4),
  ('Bacalhau à Gomes de Sá, com azeite',20.8,4.9,0.8),
  ('Bacalhau assado no forno com azeite',9,2.6,9.2),
  ('Bacalhau com natas',5.3,12.6,7.6),
  ('Bacalhau com natas, com queijo ralado',26.2,0.1,0),
  ('Bacalhau cozido',19.1,0.8,0),
  ('Bacalhau fresco cozido',17.8,0.5,0),
  ('Bacalhau fresco cru',30.2,0.2,0),
  ('Bacalhau grelhado',19,0.4,0),
  ('Bacalhau seco e salgado, demolhado cru',17.8,3.8,0.4),
  ('Baço de porco',13.8,34.6,0),
  ('Bacon',22.2,31.5,0),
  ('Bacon, grelhado sem adição de sal',11.2,2.8,51.8),
  ('Bagas goji secas',1.6,0.4,21.8),
  ('Banana',0,99.5,0),
  ('Banha de porco',0,0,89.5),
  ('Base em pó para bebida de ananás',0,0,88.9),
  ('Base em pó para bebida de laranja',2.5,0,19.2),
  ('Batata assada com pele, sem sal (só a polpa)',3.2,4.8,24.8),
  ('Batata assada no forno',2.4,0,18.5),
  ('Batata crua',1,0,28.3),
  ('Batata doce assada',1,0,28.3),
  ('Batata doce crua',2,3.1,14.5),
  ('Batata estufada com cebola, azeite e óleo alimentar',0.5,0.3,85),
  ('Batata, fécula',3.7,10.8,27.6),
  ('Batata frita caseira (em palitos)',5.7,38.1,39),
  ('Batata frita, de pacote (em rodelas)',3.6,2.1,4.2),
  ('Bebida à base de soja com açúcar, com cálcio, sal e aromas',3.8,2.2,6.4),
  ('Bebida à base de soja com açúcar, sal e aromas',3.7,2.2,0.4),
  ('Bebida à base de soja natural, sem açúcar e sem sal',0,0,9),
  ('Bebida refrigerante, cola',0,0,0),
  ('Bebida refrigerante, cola sem açúcar',0,0,7),
  ('Bebida refrigerante, gasosa',0,0,10.5),
  ('Bebida refrigerante, laranja',1,0,1),
  ('Beldroega crua',21,1.4,5.4),
  ('Berbigão aberto ao natural sem sal',10.5,0.7,2.7),
  ('Berbigão cru',1.1,0.2,2.4),
  ('Beringela crua',2,7.1,4.3),
  ('Beringela grelhada com azeite',19.5,2.7,0),
  ('Besugo cru',1,0,3.4),
  ('Beterraba (raiz) cozida sem sal',1,0,3.5),
  ('Beterraba (raiz) crua',23.1,10.1,0.2),
  ('Bife de atum fresco, estufado com azeite e vinho',21.1,3.5,0),
  ('Bife de cavalo, alcatra crua',23.3,9.3,0),
  ('Bife de cavalo, alcatra frita com manteiga',23.3,9.2,0),
  ('Bife de cavalo, alcatra frita com margarina',24.7,5.4,0),
  ('Bife de cavalo, alcatra frita, sem molho',17.1,8.1,0.4),
  ('Bife de espadarte, estufado com azeite e vinho',16.7,14.2,0.7),
  ('Bife de porco grelhado',16.9,16.5,1.6),
  ('Bife de vaca à café',16,33.3,0.9),
  ('Bife de vaca à Marrare com manteiga',16,32.8,0.8),
  ('Bife de vaca à Marrare com margarina',23.5,14.5,0.5),
  ('Bife de vaca com ovo a cavalo com banha',23.9,11.1,0.6),
  ('Bife de vaca com ovo a cavalo com manteiga',20.9,4.3,0),
  ('Bife de vaca (valor médio de acém, alcatra e lombo) cru',24.2,11.5,0.1),
  ('Bife de vaca (valor médio de acém, alcatra e lombo) frito com manteiga',28.8,7.5,0),
  ('Bife de vaca (valor médio de acém, alcatra e lombo) frito, sem molho',26.4,6.4,0),
  ('Bife de vaca (valor médio de acém, alcatra e lombo) grelhado',19.9,7.6,0.2),
  ('Bife de vitela cru',19,16.4,0.4),
  ('Bife de vitela frito',5.4,16.5,69.7),
  ('Biscoitos, argolas',6.7,11,73.4),
  ('Biscoitos caseiros',6.7,4.4,77.9),
  ('Biscoitos limão',5.2,1.8,84.1),
  ('Biscoitos, línguas de gato',5.8,20.7,65.1),
  ('Biscoitos, línguas de veado',11.5,7.2,66.6),
  ('Biscoitos, palitos la Reine',9.8,17.8,61),
  ('Bolacha água e sal',10,18.3,57.5),
  ('Bolacha aveia',7.1,19.6,70.1),
  ('Bolacha "Belga"',5.7,19.8,65.4),
  ('Bolacha chocolate',10.8,16.2,61.6),
  ('Bolacha "Cream cracker"',8.8,15.6,65.6),
  ('Bolacha integral (trigo)',6.2,21.3,65.2),
  ('Bolacha manteiga',8.4,12.2,72),
  ('Bolacha Maria',7.3,14.4,68.5),
  ('Bolacha torrada',3.2,36.4,55.3),
  ('Bolacha "waffer" baunilha',6.8,21.5,43.7),
  ('Bola de Berlim sem creme',4.4,14.8,62.7),
  ('Bolo de arroz',3.9,20.7,46.3),
  ('Bolo de bolacha Maria',7.4,26.4,47),
  ('Bolo de chocolate',4.2,31,37.8),
  ('Bolo de coco',5.9,4.1,71.6),
  ('Bolo ferradura',5.1,13.9,57),
  ('Bolo inglês',7.9,14.9,57.4),
  ('Bolo-Rei',0,0,0),
  ('Brandy',2.8,0.7,1.3),
  ('Brócolos cozidos',3.4,0.8,1.5),
  ('Brócolos crus',12.1,1.9,65.6),
  ('Bulgur',17.8,0.2,2.3),
  ('Búzio cru',14.3,32.9,0.3),
  ('Cabeça de porco',20,0.2,0),
  ('Cação cru',24,7,2.7),
  ('Cação frito',19.6,23.4,11.1),
  ('Cacau em pó',21.3,5.6,0.3),
  ('Cachaço de vaca cru',18.3,0.7,0),
  ('Cachucho cru',0.4,0.1,0.3),
  ('Café, infusão - bica (3 marcas)',0.2,0,0.3),
  ('Café, infusão - café de cafeteira (3 marcas)',0.2,0,0.3),
  ('Café, infusão - carioca (2 marcas)',0.3,0.1,0.3),
  ('Café, infusão - valor médio (bica 60% e café de cafeteira 40%)',14.9,0.5,41.1),
  ('Café solúvel em pó com cafeína',14.7,0.2,42.6),
  ('Café solúvel em pó descafeinado',4.2,2.1,7.1),
  ('Caldeirada de bacalhau',7,8.5,9.7),
  ('Caldeirada de bacalhau com enchidos e massa',11.3,4.3,8.3),
  ('Caldeirada de cabrito com azeite e banha',11.3,4,8.3),
  ('Caldeirada de cabrito com azeite e margarina',6.6,11.9,8.2),
  ('Caldeirada de enguias',7.4,21.4,5.3),
  ('Caldeirada de enguias à moda de Aveiro',7.2,9.8,4.4),
  ('Caldeirada de pargo e peixe-espada-preto',7.5,3.5,4.4),
  ('Caldeirada de peixe',6.9,2.7,5.8),
  ('Caldeirada de safio com amêijoas',4.5,3.1,7.2),
  ('Caldeirada de safio com batatas',7,2.9,9.8),
  ('Caldeirada de safio, raia e tamboril',0.3,0.3,0.2),
  ('Caldo preparado com cubo de carne de galinha (diluição 2%)',0.4,0.2,0.2),
  ('Caldo preparado com cubo de carne de vaca (diluição 2%)',22.6,0.8,0.4),
  ('Camarão cozido',20.2,1.1,0.3),
  ('Camarão cozido sem sal',17.6,0.6,0.3),
  ('Camarão cru',3.9,3.2,55.5),
  ('Canela moída',7.8,1.7,2.3),
  ('Canja de frango com aipo',10.8,1,2.1),
  ('Canja de frango com massa',2,0.4,2),
  ('Canónigos crus',13.6,8.6,1.2),
  ('Cantarilho (Redfish) assado com cebola, tomate, azeite e bacon',8.7,4.9,5.7),
  ('Cantarilho (Redfish) com batata, no forno',19.3,2.4,0),
  ('Cantarilho (Redfish) cozido',18.6,2.9,0),
  ('Cantarilho (Redfish) cru',17.3,2.7,1.1),
  ('Cantarilho (Redfish) no forno',16.1,1.4,2),
  ('Caracol cru',0.5,0.3,7.1),
  ('Carambola',19.7,2.9,0),
  ('Carapau cru',24,9.6,1),
  ('Carapau frito',26.3,3.7,0),
  ('Carapau grelhado',10.8,6.2,49.5),
  ('Cardamomo',12.7,13.8,25.2),
  ('Caril em pó',11.5,14,15.6),
  ('Carne à bolonhesa',9.7,8.1,5.6),
  ('Carne à jardineira',14.6,16.9,1.8),
  ('Carne de porco à alentejana',16,11.8,2.2),
  ('Carne de porco à alentejana sem massa de pimentão',86.2,1.5,0),
  ('Caseína',3.5,1.3,45.5),
  ('Castanha assada com sal',2.8,1,35.9),
  ('Castanha cozida sem sal',19.6,50,19.4),
  ('Castanha de caju torrada e salgada',19.6,50,19.4),
  ('Castanha de caju torrada, sem sal',9.6,66.7,2.6),
  ('Castanha do Brasil',3.1,1.1,39.8),
  ('Castanha, miolo',5.1,2,70),
  ('Castanha pilada',20.5,12.2,0),
  ('Cavala cozida',20.3,13.4,0),
  ('Cavala crua',24,9.6,0),
  ('Cavala em filetes, conserva em azeite',18.5,12.2,0.6),
  ('Cavala grelhada',12.9,14.3,2.3),
  ('Cavala no forno',1,0.2,2.4),
  ('Cebola cozida',0.9,0.2,3.1),
  ('Cebola crua',1.9,11.2,6.2),
  ('Cebola frita com óleo alimentar',2.8,0.6,1.7),
  ('Cebolinho fresco',0.6,0.1,4.8),
  ('Cenoura baby crua',0.7,0,3.6),
  ('Cenoura cozida',0.6,0,4.4),
  ('Cenoura crua',15.1,3.4,39.8),
  ('Cereal de pequeno almoço à base de farelo de trigo (tipo "All-Bran")',10.7,2,71.5),
  ('Cereal de pequeno almoço de trigo integral tipo "Weetabix"',4,1,12),
  ('Cerefólio fresco',0.8,0.7,13.3),
  ('Cereja (4 variedades)',0.4,0.2,28.7),
  ('Cereja, conserva em calda de açúcar',0.4,0.2,79.9),
  ('Cereja, cristalizada',4.4,3.8,72.6),
  ('Cereja desidratada',0.4,0,0.5),
  ('Cerveja branca',0.5,0,0.6),
  ('Cerveja preta',0.3,0,1.5),
  ('Cerveja sem álcool',0.1,0,0),
  ('Chá, infusão, preto',0.1,0,0),
  ('Chá, infusão, verde',20.3,12.6,0.2),
  ('Chambão de vitela cru',9.1,16.3,39.3),
  ('Chamuça',18.9,5.4,0),
  ('Cherne cozido',17.9,6.7,0),
  ('Cherne cru',24.1,6.3,0),
  ('Cherne grelhado',21.1,3,0),
  ('Chicharro cozido',19.7,2.9,0),
  ('Chicharro cru',26.3,3.7,0),
  ('Chicharro grelhado',1,0.1,0.9),
  ('Chicória crua',16.1,33.8,0.2),
  ('Chispe de porco',18.9,0.4,0),
  ('Choco cru',25.8,0.6,0),
  ('Choco grelhado',8,33.9,53.1),
  ('Chocolate de leite',5.4,30.5,44),
  ('Chocolate em barra, culinária',4.2,20.3,63.8),
  ('Chocolate em pó',5.2,31.7,52.6),
  ('Chocolate negro (aproximadamente 50% cacau)',20,44.1,0),
  ('Chouriço de carne de porco, cru',15.4,53.6,0),
  ('Chouriço de carne de porco, gordo, cru',24.8,26.1,0),
  ('Chouriço de carne de porco, magro, cozido sem adição de sal',24.5,34.5,0),
  ('Chouriço de carne de porco, magro, cru',31.6,24.1,0),
  ('Chouriço de carne de porco, magro, grelhado sem adição de sal',11.2,24.2,0),
  ('Chouriço de sangue cozido sem adição de sal',11,31.6,0),
  ('Chouriço de sangue, cru',0.8,0.1,2.9),
  ('Chuchu',1.3,0.3,1.1),
  ('Chucrute',11,0.3,0),
  ('Clara de ovo de galinha, crua',10.5,0,1),
  ('Clara de ovo de galinha, pasteurizada',0.8,0.2,11.1),
  ('Clementina',5.6,62,6.4),
  ('Coco seco, ralado',22.1,3.4,0),
  ('Codorniz carne sem pele, crua',21.5,9.3,0),
  ('Codorniz com pele, crua',25.6,13.4,0.7),
  ('Codorniz com pele, estufada com azeite',24.5,11.6,0),
  ('Codorniz com pele, grelhada',12.3,12.7,1.6),
  ('Coelho à caçador',20.3,4,0),
  ('Coelho cru',11.3,11.6,1.4),
  ('Coelho em vinha de alhos',26.6,10.2,0.9),
  ('Coelho estufado',26.6,11,0.9),
  ('Coelho estufado com azeite',26.6,9.5,0.9),
  ('Coelho estufado com margarina',2.4,0.6,1.8),
  ('Coentros crus',1.8,0.5,0.5),
  ('Cogumelos crus',2.1,0.4,0),
  ('Cogumelos enlatados, escorridos',2.4,16.2,0.3),
  ('Cogumelos fritos com óleo alimentar',14.8,13,35),
  ('Colorau',18,22,34),
  ('Cominhos',0.3,0,49.2),
  ('Compota de ameixa',0.5,0.1,50.8),
  ('Compota de ananás',0.4,0,61.9),
  ('Compota de cereja',0.4,0,58.9),
  ('Compota de damasco',0.4,0,59.5),
  ('Compota de laranja',5.7,6.4,18.5),
  ('Condimento de mostarda',15.6,9.3,0.7),
  ('Coração de galinha cru',18.4,4.4,0),
  ('Coração de porco, cru',20.9,10.5,1),
  ('Coração de porco, estufado com banha e margarina',23.4,3.3,0),
  ('Coração de vaca, cozido',17,2.7,0),
  ('Coração de vaca, cru',17.7,7.8,0.9),
  ('Coração de vaca, estufado com banha e margarina',16.8,3.6,0),
  ('Coração de vitela, cru',20.7,1.4,0),
  ('Corvina cozida',20.4,1.4,0),
  ('Corvina crua',23.9,2.7,0),
  ('Costeleta de cabrito crua',30.9,3,0),
  ('Costeleta de cabrito grelhada',20.8,7.5,0),
  ('Costeleta de carneiro, crua',17.3,31.8,0),
  ('Costeleta de porco gorda crua',24.3,23.1,0),
  ('Costeleta de porco gorda grelhada',18.1,14.4,0.8),
  ('Costeleta de porco grelhada',19.8,15.8,0),
  ('Costeleta de porco meio gorda crua',21.1,20.5,0.7),
  ('Costeleta de porco meio gorda estufada',21.1,20.7,0.7),
  ('Costeleta de porco meio gorda estufada com azeite e banha',21.1,20.4,0.7),
  ('Costeleta de porco meio gorda estufada com azeite e margarina',21.1,19.9,0.7),
  ('Costeleta de porco meio gorda estufada com margarina',21.1,20.7,0.7),
  ('Costeleta de porco meio gorda estufada com óleo alimentar e banha',26.9,19.6,0),
  ('Costeleta de porco meio gorda estufada, sem molho',22.1,24.1,8.6),
  ('Costeleta de porco meio gorda frita panada',27,17,0),
  ('Costeleta de porco meio gorda grelhada',20,4.5,0),
  ('Costeleta de vitela crua',23.4,9.9,0),
  ('Costeleta de vitela frita com margarina',19.7,5.3,3.4),
  ('Costeleta de vitela frita panada',24.3,6.9,0),
  ('Costeleta de vitela frita, sem molho',25.2,3.3,0),
  ('Costeleta de vitela grelhada',23.3,15.6,0),
  ('Costeleta ou perna de borrego assada com azeite e margarina',23.3,14.5,0),
  ('Costeleta ou perna de borrego assada com margarina',24.1,8,0),
  ('Costeleta ou perna de borrego, assada, sem molho',26.5,5.7,0),
  ('Costeleta ou perna de borrego, cozida',19.7,5,0),
  ('Costeleta ou perna de borrego, crua',16.2,12,1.6),
  ('Costeleta ou perna de borrego, estufada com azeite e margarina',16.2,11.1,1.6),
  ('Costeleta ou perna de borrego, estufada com margarina',25.5,9.2,0),
  ('Costeleta ou perna de borrego, estufada sem molho',24.5,7.6,0),
  ('Costeleta ou perna de borrego frita com margarina, sem molho',25.7,5.5,0),
  ('Costeleta ou perna de borrego, grelhada',24.7,8.4,0),
  ('Costeleta ou perna de carneiro magra frita com margarina, sem molho',1.7,0.4,2.2),
  ('Couve-branca cozida',1.4,0.4,3.5),
  ('Couve-branca crua',2.9,1.3,3.5),
  ('Couve-de-Bruxelas cozida',3.5,1.4,4),
  ('Couve-de-Bruxelas crua',1.6,0.2,2.3),
  ('Couve-flor cozida',3.7,0.2,3.3),
  ('Couve-flor crua',2.1,0.4,2.9),
  ('Couve-galega cozida',2.4,0.4,3.1),
  ('Couve-galega crua',2.2,0.2,1.4),
  ('Couve-lombarda cozida',2.4,0.2,2.1),
  ('Couve-lombarda crua',2.1,0.4,2.5),
  ('Couve-portuguesa cozida',2.2,0.4,3.5),
  ('Couve-portuguesa crua',2,0,3.9),
  ('Couve-roxa crua',6.8,7,6.2),
  ('Cozido à portuguesa',11.7,13.5,20.5),
  ('Cozido à portuguesa com grão',6,20,52),
  ('Cravinho',0,59,0),
  ('Creme culinário',0,65.3,0),
  ('Creme culinário líquido, 65% gordura, com sal',3.6,1.4,1.7),
  ('Creme de camarão',3.5,2.9,1.9),
  ('Creme de camarão com natas',2.6,1.9,3),
  ('Creme de ervilhas',5.9,33.3,54.7),
  ('Creme para barrar de cacau e avelãs (8 marcas)',0.1,75,0.4),
  ('Creme vegetal culinário, 75% gordura, sem sal',0.1,35,3.2),
  ('Creme vegetal para barrar 35% gordura, com fitosteróis',1.4,37.4,0.2),
  ('Creme vegetal para barrar 37% gordura',0.3,58,0.5),
  ('Creme vegetal para barrar 58% gordura, com cálcio',0.1,70,0.5),
  ('Creme vegetal para barrar 70% gordura, 53% ácidos gordos monoinsaturados',0.1,70,0.3),
  ('Creme vegetal para barrar 70% gordura, com sal',0.1,72.1,0.4),
  ('Creme vegetal para barrar 72% gordura, 33% ácidos gordos polinsaturados',7.6,23.5,42.2),
  ('Croissant',13.2,18.8,23.1),
  ('Croquete',15.1,11.9,19.1),
  ('Croquete de carne de vaca meio-gorda',15.4,15.4,9),
  ('Cubo de carne de galinha para caldo',19.8,8,8),
  ('Cubo de carne de vaca para caldo',1.6,0.3,2),
  ('Curgete crua',2,4.8,2.5),
  ('Curgete frita com óleo alimentar',0.8,0.1,8.5),
  ('Damasco',0.5,0.1,39.3),
  ('Damasco, conserva em calda de açúcar',5.4,0.9,41.2),
  ('Damasco seco',0.6,0,14.8),
  ('Dióspiro',3.3,0,80.8),
  ('Dióspiro desidratado',0.2,0,64.9),
  ('Doce de cereja',0.5,0,57.4),
  ('Doce de damasco',0.4,0,59.7),
  ('Doce de framboesa',0.4,0,64.8),
  ('Doce de ginja',0.2,0,59),
  ('Doce de maçã',0.2,0,60.5),
  ('Doce de morango',0.4,0,51.3),
  ('Doce de pêssego',6.6,21.7,43),
  ('Donut',6,14.5,47),
  ('Donut recheado com doce de fruta',20.8,12.5,0),
  ('Dourada cozida',19.7,9.8,0),
  ('Dourada crua',22.3,9.9,0),
  ('Éclair de chocolate',9.6,21.9,33.9),
  ('Empada',12.9,15.2,10.7),
  ('Empadão de atum',6.9,5,10.9),
  ('Empadão de bacalhau',6.6,6.3,10.7),
  ('Empadão de carne com manteiga',6.6,6.3,10.7),
  ('Empadão de carne com margarina',9.4,9.3,10.9),
  ('Empadão de carne guisada',8.7,4.5,11),
  ('Empadão de pescada e camarão',1.8,0.4,1.2),
  ('Endívia crua',13.4,27.7,0),
  ('Enguia crua',14.8,21.6,3.2),
  ('Enguia frita',26.9,14.2,0),
  ('Entrecosto de porco cozido',19.6,12.4,0),
  ('Entrecosto de porco cru',20.9,17.1,0.7),
  ('Entrecosto de porco estufado com azeite e banha',20.9,16.8,0.7),
  ('Entrecosto de porco estufado com azeite e margarina',20.9,16.3,0.7),
  ('Entrecosto de porco estufado com margarina',20.9,17.1,0.7),
  ('Entrecosto de porco estufado com óleo alimentar e banha',26.6,15.4,0),
  ('Entrecosto de porco estufado, sem molho',26.8,15.1,0),
  ('Entrecosto de porco grelhado',5.1,5.1,9.6),
  ('Ervilhas estufadas',5.6,0.5,7.5),
  ('Ervilhas, grão, congeladas cozidas',5.3,0.5,7),
  ('Ervilhas, grão, congeladas cruas',6.2,0.7,7.9),
  ('Ervilhas, grão, frescas cozidas',6.4,0.7,8.6),
  ('Ervilhas, grão, frescas cruas',6.9,0.4,18.1),
  ('Ervilhas secas cozidas',22.7,1.3,49.4),
  ('Ervilhas secas cruas',2.8,0.2,3.5),
  ('Ervilhas, vagens cozidas',3.1,0.2,3.9),
  ('Ervilhas, vagens cruas',17.8,2.9,0),
  ('Espadarte cru',21.3,3.4,0),
  ('Espadarte grelhado',2.2,0,2.2),
  ('Espargos cozidos',2.1,0,2.7),
  ('Espargos crus',3.4,0.6,19.9),
  ('Esparguete cozido',12.1,1.9,71.1),
  ('Esparguete cru',3,3.9,17.6),
  ('Esparguete estufado com cenoura e azeite',3,3.2,17.6),
  ('Esparguete estufado com cenoura e margarina',13.6,24.8,1.3),
  ('Espetada de porco grelhada',23.5,12.8,0.8),
  ('Espetada de vaca grelhada',2.6,0.9,0.8),
  ('Espinafres crus',3.4,1.1,6.3),
  ('Estragão fresco',22.8,7.2,42.8),
  ('Estragão seco',19,0.6,0.1),
  ('Faneca crua',16.2,5.3,24.9),
  ('Farelo de trigo',3.2,0.3,85.6),
  ('Farinha de alfarroba',14.5,7.3,57),
  ('Farinha de aveia',7.8,1.2,77.3),
  ('Farinha de centeio',6.6,1.1,78.5),
  ('Farinha de centeio tipo 70',9,1.3,76),
  ('Farinha de centeio tipo 85',8.8,2.5,64.4),
  ('Farinha de cevada',14,2.3,61.8),
  ('Farinha de espelta',8.3,2.2,75.3),
  ('Farinha de milho tipo 70',1.4,0.3,84.6),
  ('Farinha de pau (mandioca)',9.6,2.4,65.2),
  ('Farinha de trigo integral',9.1,1.8,73),
  ('Farinha de trigo tipo 150',7.8,1.1,74.3),
  ('Farinha de trigo tipo 55',8.5,1.5,73.7),
  ('Farinha de trigo (valor médio tipo 150 e tipo 55)',15,9,65),
  ('Farinha láctea 5 frutos tipo "Cerelac" (com farinha de trigo)',15,9,66),
  ('Farinha láctea maçãs tipo "Cerelac" (com farinha de trigo)',15,9,68),
  ('Farinha láctea tipo "Cerelac" (com farinha de trigo)',4.8,30.7,26.4),
  ('Farinheira cozida sem adição de sal',4.8,41,26.7),
  ('Farinheira crua',8,5.9,8.4),
  ('Favada à portuguesa',6.7,0.5,7.4),
  ('Favas frescas cozidas',7.4,0.5,8.5),
  ('Favas frescas cruas',7.9,0.6,10.7),
  ('Favas secas cozidas (demolhadas)',25.8,1.3,32.8),
  ('Favas secas cruas',6.6,0.5,14.6),
  ('Feijão branco cozido (demolhado)',21,1.4,43.9),
  ('Feijão branco cru',8.8,0.7,18.1),
  ('Feijão frade (feijão miúdo) cozido (demolhado)',22.6,1.3,55.3),
  ('Feijão frade (feijão miúdo) cru',7.8,0.6,14),
  ('Feijão manteiga cozido (demolhado)',21.8,1.4,42.6),
  ('Feijão manteiga cru',1.8,0.3,3.5),
  ('Feijão-verde fresco cozido',1.9,0.3,3.8),
  ('Feijão-verde fresco cru',22.1,1.4,36.7),
  ('Feijão vermelho seco',13.6,7.2,13.3),
  ('Feijoada com carne de porco',13.7,7.5,13.3),
  ('Feijoada com carne de porco e de vaca',9,15.1,14.1),
  ('Feijoada com enchidos e ovos',0.9,0.5,9.8),
  ('Feijoa (polpa)',4.7,0,34.4),
  ('Fermento em pó',12.9,0.9,1),
  ('Fermento fresco de padeiro',38.3,2.5,3.2),
  ('Fermento seco de padeiro',13.8,1.6,2.7),
  ('Fiambre de aves',15.3,4.6,0),
  ('Fiambre de porco',14,5.1,1.3),
  ('Fiambre, pá',13.7,1.3,2.8),
  ('Fiambre, peito de frango',13.8,1.9,2.6),
  ('Fiambre, peito de peru',16.5,4.1,1.2),
  ('Fiambre, perna',17.7,2.3,0),
  ('Fígado de galinha',20.9,5,0),
  ('Fígado de porco, cru',23.2,13.1,0),
  ('Fígado de porco, frito com margarina e banha',25.2,8.8,0),
  ('Fígado de porco, frito, sem molho',26.3,6.3,0),
  ('Fígado de porco, grelhado',20.9,4.4,2.1),
  ('Fígado de vaca, cru',24.5,7,2.5),
  ('Fígado de vaca, frito, sem molho',20.3,3.5,1.5),
  ('Fígado de vitela, cru',22.6,11.5,1.7),
  ('Fígado de vitela, frito com banha e manteiga',24.6,8.3,1.5),
  ('Fígado de vitela, frito, sem molho',25.7,4.7,1.9),
  ('Fígado de vitela, grelhado',0.9,0.5,16.3),
  ('Figo (5 variedades)',0.5,0.4,71.2),
  ('Figo cristalizado',2.3,0.6,58.3),
  ('Figo seco',19.2,10.7,5.1),
  ('Filetes de bacalhau fritos',1.8,0.6,11.7),
  ('Fisális',7,1.5,83.4),
  ('Flocos de arroz',13.5,5.8,61.7),
  ('Flocos de aveia',12,2,69),
  ('Flocos de centeio',10.4,6.3,69.1),
  ('Flocos de cereais e frutos secos tipo "Muesli"',8.3,2,64.4),
  ('Flocos de cevada',7.9,1.1,81.1),
  ('Flocos de milho tipo "Corn Flakes"',14,2.5,69),
  ('Flocos de trigo',9,1.5,76.3),
  ('Flocos de trigo com figos tipo "Nestum"',8.2,1,84.6),
  ('Flocos de trigo com mel tipo "Nestum"',7.5,1.3,79.2),
  ('Flocos de trigo e arroz enriquecidos com vitaminas, cálcio e ferro',10.2,1.9,64.2),
  ('Flocos de trigo integral tipo "All-Bran Flakes"',0,0,0),
  ('Flor de sal',3.5,0.5,3.7),
  ('Folhas de rabanete cruas',0.9,0.6,5.1),
  ('Framboesa',5.4,3.6,30.9),
  ('Framboesa desidratada',13.3,17.7,6.5),
  ('Francesinha, com molho',27.2,10.3,0),
  ('Frango (1/4) peito e asa com pele, cozidos',20.4,12.7,0),
  ('Frango (1/4), peito e asa com pele, crus',18.5,13.5,1.7),
  ('Frango (1/4) peito e asa com pele, estufados com azeite e margarina',18.5,13.2,1.7),
  ('Frango (1/4) peito e asa com pele, estufados com margarina',29.2,11.8,0),
  ('Frango (1/4) peito e asa com pele, estufados sem molho',28.7,13.4,0),
  ('Frango (1/4) peito e asa com pele, grelhados',26.9,13.7,0),
  ('Frango (1/4) perna com costa e pele, assada sem molho',25.5,10.6,0),
  ('Frango (1/4) perna com costa e pele, cozida',19.1,13,0),
  ('Frango (1/4), perna com costa e pele, crua',17.3,13.8,1.7),
  ('Frango (1/4) perna com costa e pele, estufada com azeite e margarina',17.3,13.5,1.7),
  ('Frango (1/4) perna com costa e pele, estufada com margarina',26.9,11.9,0),
  ('Frango (1/4) perna com costa e pele, estufada sem molho',26.9,13.7,0),
  ('Frango (1/4), perna com costa e pele, grelhada',27.6,14.3,0),
  ('Frango inteiro com pele, assado sem molho',26.1,11.1,0),
  ('Frango inteiro com pele, cozido',19.6,13.6,0),
  ('Frango inteiro com pele, cru',19.1,15.4,1.8),
  ('Frango inteiro com pele, estufado com azeite e margarina',19.1,15.1,1.8),
  ('Frango inteiro com pele, estufado com margarina',28.8,13.1,0),
  ('Frango inteiro com pele, estufado sem molho',27.6,14.3,0),
  ('Frango inteiro com pele, grelhado',32.8,4.2,0),
  ('Frango inteiro sem pele, cozido',22.9,2,0),
  ('Frango inteiro sem pele, cru',21,4.1,1.7),
  ('Frango inteiro sem pele, estufado com azeite e margarina',21,3.8,1.7),
  ('Frango inteiro sem pele, estufado com margarina',33.2,5.8,0),
  ('Frango inteiro sem pele, estufado sem molho',31,4.9,0),
  ('Frango inteiro sem pele, grelhado',9.7,48.3,0),
  ('Frango, pele crua',2.8,0.4,2.6),
  ('Funcho fresco',23.4,6.5,0),
  ('Galinha de angola com pele, crua',21.5,0.2,0),
  ('Gamba crua',20.8,2,0),
  ('Garoupa cozida',20.5,1.4,0),
  ('Garoupa crua',25.9,1.9,0),
  ('Garoupa grelhada',5.1,21.2,36.5),
  ('Gelado caseiro com bolachas e natas',7.9,12.4,28.7),
  ('Gelado caseiro com palitos la Reine',0.4,0,32.6),
  ('Gelado de água (sorvete)',3.6,10.9,21.7),
  ('Gelado de leite',87,0.1,0),
  ('Gelatina desidratada (pó ou folha)',2.2,0,21.6),
  ('Gelatina preparada com ananás em conserva',2.6,0.1,17.4),
  ('Gelatina preparada com laranja e sumo de laranja',0.3,0,68),
  ('Geleia de casca de laranja',16,30.9,0),
  ('Gema de ovo de galinha, crua',15.3,25.2,1.3),
  ('Gema de ovo de galinha, pasteurizada',1.8,0.8,15.8),
  ('Gengibre fresco',28.1,9.6,41.8),
  ('Gérmen de trigo',0.9,0.3,11.5),
  ('Ginja',0,0,0),
  ('Gin - Rum- Whisky',0.8,0.5,5),
  ('Goiaba crua, polpa',14.8,5.1,1.5),
  ('Goraz assado com cebola, tomate, azeite e óleo alimentar',19.2,3.5,0),
  ('Goraz cozido',18.8,2.7,0),
  ('Goraz cru',22.4,3.2,0),
  ('Goraz grelhado',18.7,2.7,0.7),
  ('Goraz no forno',8.4,2.1,16.7),
  ('Grão-de-bico cozido (demolhado)',19,5,51.4),
  ('Grão-de-bico cru',1.9,0.4,1.5),
  ('Grelos de couve cozidos',2.4,0.4,2.5),
  ('Grelos de couve crus',1.8,0.4,1.3),
  ('Grelos de nabo cozidos',2.4,0.5,2.3),
  ('Grelos de nabo crus',10.7,8.7,67),
  ('Gressino',1.1,0.5,5),
  ('Groselha',8,5.3,19.8),
  ('Hambúrguer de feijão manteiga frito com azeite',8,5.3,19.8),
  ('Hambúrguer de feijão manteiga frito com óleo de milho',8.8,0.7,3),
  ('Hambúrguer de peru, frito',27.5,17.1,0),
  ('Hambúrguer de porco, frito, sem molho',27.8,16.6,0),
  ('Hambúrguer de porco, grelhado',20.2,6.8,0),
  ('Hambúrguer de vaca, cru',19.1,13.8,1.2),
  ('Hambúrguer de vaca, frito',27.3,8.2,0),
  ('Hambúrguer de vaca, grelhado',3.8,0.7,5.3),
  ('Hortelã fresca',13.7,3.1,1.4),
  ('Imperador assado com cebola, tomate, azeite e óleo alimentar',19.9,0.5,0),
  ('Imperador cozido',19,0.4,0),
  ('Imperador cru',23,0.5,0),
  ('Imperador grelhado',1.5,0.3,25.7),
  ('Inhame cru',3.9,3.6,8.5),
  ('Iogurte gordo, aromatizado, açucarado',4.2,3.2,12.4),
  ('Iogurte gordo, com polpa e/ou pedaços de fruta, açucarado',4.2,3.2,15.8),
  ('Iogurte gordo, com polpa e/ou pedaços de fruta e cereais açucarado',2.7,5,15),
  ('Iogurte grego com fruta açucarado',5.3,2,3.9),
  ('Iogurte grego magro natural',1.4,6.6,4.4),
  ('Iogurte grego natural',3.2,0.3,11.6),
  ('Iogurte líquido magro, aromatizado, açucarado',3,1.3,11.5),
  ('Iogurte líquido meio gordo, aromatizado, açucarado',3.1,1.4,11.2),
  ('Iogurte líquido meio gordo, natural, açucarado',5,0.1,11.8),
  ('Iogurte magro, aromatizado, açucarado',4.3,0.4,5.7),
  ('Iogurte magro, com cereais e edulcorantes',4.6,0.2,5.2),
  ('Iogurte magro, natural',5,0.1,6.3),
  ('Iogurte magro, natural, com edulcorantes',4.3,1.8,11.3),
  ('Iogurte meio gordo, aromatizado, açucarado',4.3,1.7,14.6),
  ('Iogurte meio gordo, com polpa e/ou pedaços de fruta, açucarado',4.2,1.8,5),
  ('Iogurte meio gordo, natural',4.7,2.1,13.1),
  ('Iogurte meio gordo, natural, açucarado',9,0,9.7),
  ('Iogurte sem lactose enriquecido em proteína, magro, aromatizado, com pedaços e/ou polpa de fruta, açucarado',3.1,0.2,16),
  ('Iogurte sem lactose líquido, magro, aromatizado, com polpa de fruta, açucarado',3.3,0.1,5),
  ('Iogurte sem lactose líquido, magro, aromatizado, com polpa de fruta, com edulcorantes',2.8,1.4,11.8),
  ('Iogurte sem lactose líquido, meio gordo, aromatizado, açucarado',2.6,1.3,12.5),
  ('Iogurte sem lactose líquido, meio gordo, aromatizado, com polpa de fruta, açucarado',2.7,1.4,11.7),
  ('Iogurte sem lactose líquido, meio gordo, natural, açucarado',4.8,0.1,4.8),
  ('Iogurte sem lactose magro, aromatizado, com pedaços e/ou polpa de fruta, com edulcorantes',4.9,0.2,5),
  ('Iogurte sem lactose magro, natural',3.5,1.5,12),
  ('Iogurte sem lactose meio gordo, aromatizado, açucarado',3.7,1.6,16.1),
  ('Iogurte sem lactose meio gordo, aromatizado, com frutos secos e cereais, açucarado',3.7,1.3,13.6),
  ('Iogurte sem lactose meio gordo, aromatizado, com pedaços e/ou polpa de fruta, açucarado',3.8,1.5,4.5),
  ('Iogurte sem lactose meio gordo, natural',3.5,1.5,12.2),
  ('Iogurte sem lactose meio gordo, natural, açucarado',21.4,6,0.1),
  ('Jarrete de porco',19.5,3.4,0),
  ('Javali cru',4.1,31.2,54),
  ('Jesuíta',20.6,0.8,0.2),
  ('Lagosta cozida',18.2,0.7,0.1),
  ('Lagosta crua',21.2,0.5,0.2),
  ('Lagostim cozido',20.9,0.5,0.2),
  ('Lagostim cru',16.7,27.4,0.1),
  ('Lampreia crua',14.3,0.7,0.6),
  ('Lapas cruas',1.1,0.2,8.9),
  ('Laranja (3 variedades)',7.7,12.4,9.2),
  ('Lasanha à bolonhesa',21.6,3,0),
  ('Lebre crua',7.8,9,56.4),
  ('Leite condensado',5.9,6.8,19.5),
  ('Leite creme',3.8,4,4.6),
  ('Leite de cabra cru',2,18.4,2.8),
  ('Leite de coco, enlatado',5.1,6.2,4.2),
  ('Leite de ovelha cru',6.6,7.8,9.8),
  ('Leite evaporado',4,3.6,4.5),
  ('Leite fermentado (Bifidus) gordo, natural',4.2,0.8,6.6),
  ('Leite fermentado (Bifidus) sem lactose enriquecido com fibra, magro, aromatizado, com pedaços e/ou polpa de fruta, com sementes e/ou cereais, com frutos secos e/ou de casca rija, com edulcorantes',4.2,3.7,4.8),
  ('Leite fermentado (Bifidus) sem lactose, gordo, natural',2.7,1.7,11),
  ('Leite fermentado (Bifidus) sem lactose líquido, meio gordo, aromatizado, com pedaços e/ou polpa de fruta, açucarado',4.9,0.4,8.2),
  ('Leite fermentado (Bifidus) sem lactose, magro, aromatizado, com pedaços e/ou polpa de fruta e/ou hortícolas, açucarado, com edulcorantes',5.3,0.4,6.2),
  ('Leite fermentado (Bifidus) sem lactose magro, natural, com edulcorantes',3.1,3.4,4.8),
  ('Leite gordo especial, pasteurizado',3,3.5,4.7),
  ('Leite gordo, pasteurizado',26.8,25.9,38.7),
  ('Leite gordo, pó',3,3.5,4.6),
  ('Leite gordo sem lactose, enriquecido com vitaminas A, D, E e B9 (ácido fólico), UHT',3,3.5,4.7),
  ('Leite gordo, UHT',1.4,3.4,7.5),
  ('Leite humano',2.3,2.8,6.3),
  ('Leite humano, colostro',1.6,3.7,6.6),
  ('Leite humano, transição',3.1,0.1,4.9),
  ('Leite magro de pastagem, UHT',35.1,0.9,52.7),
  ('Leite magro, pó',3.4,0.2,5.1),
  ('Leite magro sem lactose, UHT',3.4,0.2,4.9),
  ('Leite magro, UHT',3,1.8,7.9),
  ('Leite meio gordo aromatizado, UHT',3,1.5,5),
  ('Leite meio gordo de pastagem, UHT',30.7,13.5,45.6),
  ('Leite meio gordo, pó',3.3,1.6,5.1),
  ('Leite meio gordo sem lactose, UHT',3.3,1.6,4.9),
  ('Leite meio gordo, UHT',9.1,0.3,16.7),
  ('Lentilhas secas cozidas (demolhadas)',25.2,0.7,47.6),
  ('Lentilhas secas cruas',0.9,0.4,14.8),
  ('Lichia fresca',0,0,34.8),
  ('Licor beneditino',0,0,36),
  ('Licor de anis',0.1,0,19),
  ('Licor de ginja',0,0,24.4),
  ('Licor simples',0.7,0.2,1.7),
  ('Lima',0.5,0.3,1.9),
  ('Limão',16.3,17.2,0),
  ('Língua de porco crua',15.9,15,0),
  ('Língua de vaca, crua',19.8,20.9,0),
  ('Língua de vaca, estufada, sem molho',20.1,0.2,0),
  ('Linguado cru',24.3,6.2,2.7),
  ('Linguado frito',23.1,0.2,0),
  ('Linguado grelhado',21.5,39,0),
  ('Linguiça',27.5,11.3,0.2),
  ('Lombo de porco assado',27.5,11.1,0.2),
  ('Lombo de porco assado com azeite e margarina',28.2,10.6,0),
  ('Lombo de porco assado com margarina',27.5,11.1,0.2),
  ('Lombo de porco assado com óleo alimentar e margarina',32.7,8.8,0),
  ('Lombo de porco assado, sem molho',22.2,4.7,0),
  ('Lombo de porco cru',28.8,7.4,0),
  ('Lombo de porco frito',28.8,7.2,0),
  ('Lombo de porco frito com manteiga',28.8,7.6,0),
  ('Lombo de porco frito com margarina',25.3,12.5,8.5),
  ('Lombo de porco frito panado',29.1,8.1,0),
  ('Lombo de porco grelhado',26.2,11.1,0),
  ('Lombo de vaca magro assado com azeite e margarina',26.2,11.4,0),
  ('Lombo de vaca magro assado com azeite, manteiga e óleo alimentar',26.2,10.4,0),
  ('Lombo de vaca magro assado com margarina',26.2,11.1,0),
  ('Lombo de vaca magro assado com óleo alimentar e margarina',29.2,6.1,0),
  ('Lombo de vaca magro assado, sem molho',21,3.3,0),
  ('Lombo de vaca magro cru',11.9,6.8,2.5),
  ('Lombo de vaca magro no forno, com tomate, cebola, cenoura e alho',23,14.4,0.2),
  ('Lombo de vitela assado com azeite e margarina',23,14.4,0.2),
  ('Lombo de vitela assado com azeite, margarina e óleo alimentar',23,14.4,0.2),
  ('Lombo de vitela assado com margarina e óleo alimentar',25.1,5.6,0),
  ('Lombo de vitela assado, sem molho',19.9,7.6,0),
  ('Lombo de vitela cru',23.5,13.7,0),
  ('Lombo de vitela frito com margarina',24.9,10.6,0),
  ('Lombo de vitela frito, sem molho',25,5.6,0),
  ('Lombo de vitela grelhado',22.7,8,0.1),
  ('Lombo ou pá de cavalo assado com azeite e manteiga',22.7,7.3,0.1),
  ('Lombo ou pá de cavalo assado com margarina',24.2,4.3,0),
  ('Lombo ou pá de cavalo assado, sem molho',19.6,2.3,0),
  ('Lombo ou pá de cavalo cru',21.6,8,0),
  ('Lombo ou pá de cavalo frito com manteiga',21.6,7.8,0),
  ('Lombo ou pá de cavalo frito com margarina',15.8,0.9,0),
  ('Lula crua',16.1,6.3,2.9),
  ('Lula estufada com cebola, tomate e azeite',32.5,1.6,0),
  ('Maçã assada com açúcar',0.3,0.5,15.7),
  ('Maçã assada sem açúcar',0.2,0.5,13.4),
  ('Maçã com casca',0.2,0.5,17),
  ('Maçã cozida com açúcar',0.2,0.5,10.5),
  ('Maçã cozida sem açúcar',1.1,2.9,74.5),
  ('Maçã desidratada',0.2,0.5,13.1),
  ('Maçã (média com e sem casca)',0.8,0.3,57.1),
  ('Maçã seca',0.2,0.5,12.7),
  ('Maçã sem casca',4.9,22.6,54.7),
  ('Madalena',4,71.2,0),
  ('Maionese caseira, com ovo e azeite',3.9,69.8,0),
  ('Maionese caseira, com ovo e óleo de soja',1.8,0.3,4.2),
  ('Malagueta vermelha fresca',1,0.3,33.8),
  ('Mandioca crua',0.5,0.3,11.7),
  ('Manga',2.9,1.7,67.4),
  ('Manga desidratada',3.1,0.8,5.1),
  ('Manjericão fresco',23,4.1,10),
  ('Manjericão seco',12.7,7,42.5),
  ('Manjerona seca',0.1,81.8,0.7),
  ('Manteiga com sal',0.1,83,0.7),
  ('Manteiga sem sal',2.6,0.4,5.7),
  ('Maracujá',0.1,82,0.4),
  ('Margarina',0.1,58,0.3),
  ('Margarina 3/4, de girassol',0.1,85.5,0.4),
  ('Margarina culinária para folhados, com sal',0.1,80.5,0.4),
  ('Margarina industrial para pastelaria, com sal',0.1,80,0.4),
  ('Margarina vegetal culinária, 80% gordura, com sal',1,74.3,4.4),
  ('Margarina vegetal culinária, com alho e sal',0.1,0,69.7),
  ('Marmelada',0.3,0.2,9.3),
  ('Marmelo',17.9,0.1,0),
  ('Maruca cozida',17.2,0.1,0),
  ('Maruca crua',2.8,0.6,13.3),
  ('Massa com ovo cozida',13.9,3.1,67.6),
  ('Massa com ovo crua',2.6,1,4.4),
  ('Massa de pimentão',5,27.5,31.8),
  ('Massa folhada, congelada',12.4,1.8,70),
  ('Massa miúda crua',4,0.7,22.6),
  ('Massa para lasanha cozida',12,2.1,71.4),
  ('Massa para lasanha crua',7.8,4.8,52.5),
  ('Massa para pizza',5.5,29.2,52.4),
  ('Massa quebrada para quiche',12.7,4.2,14.8),
  ('Meia-desfeita de bacalhau',0.5,0,78),
  ('Mel',0.6,0.1,66.6),
  ('Melaço',0.4,0.2,5.5),
  ('Melancia',0.6,0.3,5.7),
  ('Melão (3 variedades)',0.3,0,77.4),
  ('Mel de cana',0.6,0.1,4.2),
  ('Meloa',4.1,0.5,83),
  ('Merengue',16.8,2.1,2.8),
  ('Mexilhão cozido sem sal',12.1,1.5,2),
  ('Mexilhão cru',0.4,0.2,90.2),
  ('Milho, amido (pó)',2.8,1.7,18.4),
  ('Milho doce em conserva',9.3,4.9,70.3),
  ('Milho, grão seco cru',0.9,41.6,0.4),
  ('Minarina (meia margarina)',0.5,0.6,6.4),
  ('Mirtilo',3.7,4.4,46.8),
  ('Mirtilo desidratado',4,8.4,9.6),
  ('Molho "Béchamel" com manteiga',3.6,9.5,9.9),
  ('Molho "Béchamel" com margarina',1.1,9.2,6.8),
  ('Molho branco com caldo de carne de vaca',4.4,16.8,18.5),
  ('Molho branco com margarina',2,41,0.4),
  ('Molho de bife frito com manteiga',2.1,64,0.3),
  ('Molho de carne de vaca assada com azeite e margarina',1.9,56,0.4),
  ('Molho de carne de vaca assada com margarina',1.7,27.9,0.4),
  ('Molho de carne de vaca estufada com azeite e margarina',1.3,28.5,1.3),
  ('Molho de carne de vaca estufada com vegetais, azeite e margarina',2.2,60.2,0),
  ('Molho de lombo de porco frito com banha',2.3,54.3,0.1),
  ('Molho de lombo de porco frito com banha e margarina',2.3,48.5,0.2),
  ('Molho de lombo de porco frito com margarina',2.2,37.8,0.2),
  ('Molho de lombo de vaca frito com creme vegetal sem sal',2.2,40.3,0.2),
  ('Molho de lombo de vaca frito com margarina',2.6,40.2,18),
  ('Molho de mostarda',4.7,0,17.3),
  ('Molho de soja',1.1,8.8,4.9),
  ('Molho de tomate',1.7,0.3,26.9),
  ('Molho de tomate, "ketchup"',0.2,71.8,0.2),
  ('Molho de vinagrete',1.1,2.6,4.8),
  ('Molho para francesinha',0.7,25.6,2.3),
  ('Molho verde',0.6,0.4,5.3),
  ('Morango',5.8,3.8,50.9),
  ('Morango desidratado',12,29.5,12),
  ('Morcela crua',12.9,25.9,13.1),
  ('Morcela grelhada sem adição de sal',18.3,33.2,1.7),
  ('Mortadela',9.5,13.1,31),
  ('Mousse de chocolate',2.8,0.1,16.3),
  ('Múcua (fruto do embondeiro, baobab)',2,0,1),
  ('Nabiça crua',0.4,0.4,2.3),
  ('Nabo (raiz) cozido',0.4,0.4,3),
  ('Nabo (raiz) cru',1.9,32,2.7),
  ('Nata maturada pasteurizada 30% gordura',2.2,34,2.1),
  ('Nata para bater pasteurizada 34% gordura',2,33,2.9),
  ('Nata pasteurizada 33% gordura',2,36,1.9),
  ('Nata pasteurizada 36% gordura',2,15,2.4),
  ('Nata pasteurizada para café, 15% gordura',1.8,35,3.1),
  ('Nata UHT 35% gordura',0.2,0.1,12.9),
  ('Néctar de alperce',0.2,0.1,10.5),
  ('Néctar de ananás',0.2,0.1,9.6),
  ('Néctar de laranja',0.1,0.1,11.3),
  ('Néctar de maçã',0.1,0.2,4.6),
  ('Néctar de maçã, "light"',0.2,0.1,11),
  ('Néctar de pera',0.2,0.1,11.7),
  ('Néctar de pêssego',0.1,0.1,3.5),
  ('Néctar de pêssego, "light"',0.1,0.1,10.8),
  ('Néctar de "tutti - frutti"',1.4,0.1,8.7),
  ('Nectarina',0.4,0.4,10.2),
  ('Nêspera',8,76,5.1),
  ('Noz macadâmia',16.7,67.5,3.6),
  ('Noz, miolo',5.8,36.3,28.5),
  ('Noz-moscada',9.4,72.6,5.4),
  ('Noz pecan',0,99.5,0),
  ('Óleo alimentar',0,98.5,0),
  ('Óleo "Becel"',0,98.5,0),
  ('Óleo de amendoim',0,100,0),
  ('Óleo de coco',0,99.5,0),
  ('Óleo de girassol',0,100,0),
  ('Óleo de linhaça',0,100,0),
  ('Óleo de palma',0,98.5,0),
  ('Óleo de soja',0,99.5,0),
  ('Óleos de milho',12,9.5,0.2),
  ('Omelete',13,16.3,0),
  ('Omelete com manteiga',13,16.2,0),
  ('Omelete com margarina',9,4.3,26.4),
  ('Orégão seco',26,2.5,0.3),
  ('Orelha de porco, crua',8.6,1.7,3.9),
  ('Ostra, crua',21.7,1.9,0),
  ('Ovas de bacalhau cruas',14.3,2.9,0),
  ('Ovas de pescada cruas',12.9,10.7,0.4),
  ('Ovo de codorniz, cru',13,10.8,0),
  ('Ovo de galinha, cozido',13,10.9,0),
  ('Ovo de galinha, escalfado',13.7,15.4,0),
  ('Ovo de galinha, estrelado',13.8,15.1,0),
  ('Ovo de galinha, estrelado com azeite',13.7,15.5,0),
  ('Ovo de galinha, estrelado com manteiga',13.7,15.5,0),
  ('Ovo de galinha, estrelado com margarina',13,10.8,0),
  ('Ovo de galinha inteiro, cru',11.9,9.3,0),
  ('Ovo de galinha líquido, pasteurizado',13,16.1,0),
  ('Ovo de galinha, mexido com manteiga',13,16,0),
  ('Ovo de galinha, mexido com margarina',11,18.3,0.9),
  ('Ovo mexido com leite e margarina',24.3,24.6,0),
  ('Pá de carneiro, assada com azeite e margarina',24.3,23.6,0),
  ('Pá de carneiro, assada com margarina',25.1,11.3,0),
  ('Pá de carneiro assada, sem molho',27.6,14.2,0),
  ('Pá de carneiro, cozida',20.5,12.6,0),
  ('Pá de carneiro, crua',27.6,14.2,0),
  ('Pá de carneiro, estufada sem molho',23.3,4.9,0.3),
  ('Pá de vitela crua',29.2,19,0),
  ('Paio de lombo',22.8,30,0),
  ('Paio de lombo entremeado',5.9,0.8,56.4),
  ('Pão de centeio',7.7,2.1,41.3),
  ('Pão de centeio integral',8.3,2,58.3),
  ('Pão de forma, de trigo com passas',8.7,2.7,54.5),
  ('Pão de forma, de trigo enriquecido',7.7,1.9,51.4),
  ('Pão de leite (trigo)',9.6,8,62.2),
  ('Pão de ló',5.3,1.2,37.2),
  ('Pão de milho',9,1.4,53.8),
  ('Pão de mistura de trigo e centeio',8.4,2.2,57.3),
  ('Pão de trigo',7.6,3,39.9),
  ('Pão de trigo integral',7.4,2.6,44),
  ('Pão de trigo integral com passas',7.7,4,43.2),
  ('Pão de trigo integral com sementes de sésamo',9.4,2.8,38.2),
  ('Pão de trigo integral com soja',7,1.2,51),
  ('Pão do coração (trigo)',7.7,1.1,42.7),
  ('Pão pita',11.2,2.3,71.6),
  ('Pão ralado',0.6,0.1,9.1),
  ('Papaia',4.8,0.8,73.3),
  ('Papaia desidratada',15.9,6.7,1.4),
  ('Pargo legítimo assado com cebola, tomate e azeite',19.8,0.3,0),
  ('Pargo legítimo cozido',19.4,0.2,0),
  ('Pargo legítimo cru',15.2,7.1,1.4),
  ('Pargo mulato assado com cebola, tomate e azeite',19,1,0),
  ('Pargo mulato cozido',18.5,0.7,0),
  ('Pargo mulato cru',27,17.6,4.6),
  ('Pasta de fígado de aves (paté), caseira',10,34.5,3.2),
  ('Pasta de fígado de porco (paté)',13.8,13.4,12.3),
  ('Pastel de bacalhau',6.8,9.4,52),
  ('Pastel de feijão',2.9,10.2,48.5),
  ('Pastel de nata',7.1,26,37.4),
  ('Pastel folhado',6.9,0,75.1),
  ('Pastilha elástica',18.5,30.3,0),
  ('Pato com pele, assado sem molho',12.3,38.3,0),
  ('Pato com pele, cru',36.2,14.6,0),
  ('Pato sem pele, assado com margarina',19.3,6.2,0),
  ('Pato sem pele, cru',27.2,13.7,0),
  ('Pato sem pele, estufado com margarina',38,20.4,0),
  ('Pé de porco, cru',20.5,3.8,0),
  ('Peito de cabrito cru',23.3,8.4,0.8),
  ('Peito de cabrito estufado com azeite e margarina',23.3,8.8,0.7),
  ('Peito de cabrito estufado com azeite e óleo alimentar',23.3,8.4,0.8),
  ('Peito de cabrito estufado com manteiga e óleo alimentar',23.3,8.4,0.8),
  ('Peito de cabrito estufado com margarina e óleo alimentar',28.4,4.4,0),
  ('Peito de cabrito estufado, sem molho',26.5,4.2,0),
  ('Peito de cabrito grelhado',23.3,26.6,0),
  ('Peito de carneiro gordo, cozido',16.8,36.5,0),
  ('Peito de carneiro gordo, cru',32.1,7.3,0),
  ('Peito de frango com pele, cozido',24.1,8.9,0),
  ('Peito de frango com pele, cru',22.1,10.3,1.7),
  ('Peito de frango com pele, estufado com azeite e margarina',22.1,10,1.7),
  ('Peito de frango com pele, estufado com margarina',34.4,8.3,0),
  ('Peito de frango com pele, estufado sem molho',34.5,1.1,0),
  ('Peito de frango sem pele, cozido',24.1,1.2,0),
  ('Peito de frango sem pele, cru',21.4,3.3,1.7),
  ('Peito de frango sem pele, estufado com azeite e margarina',21.4,3,1.7),
  ('Peito de frango sem pele, estufado com margarina',36.6,2.5,0),
  ('Peito de frango sem pele, estufado sem molho',23,4.7,0),
  ('Peito de peru com pele, cru',23.1,7.1,1.3),
  ('Peito de peru com pele, estufado com margarina',28.9,6.4,0.1),
  ('Peito de peru sem pele, assado com margarina',23.4,1.3,0),
  ('Peito de peru sem pele, cru',25.5,9.9,8.4),
  ('Peito de peru sem pele, panado',24.8,8,0),
  ('Peito de vitela magro cozido',19.6,7.6,0),
  ('Peito de vitela magro cru',22.9,12.6,0.6),
  ('Peito de vitela magro estufado',22.9,12.6,0.6),
  ('Peito de vitela magro estufado com azeite e margarina',22.9,12.6,0.6),
  ('Peito de vitela magro estufado com azeite, margarina e óleo alimentar',22.9,12.6,0.6),
  ('Peito de vitela magro estufado com margarina e óleo alimentar',26,8.3,0),
  ('Peito de vitela magro estufado, sem molho',20.3,4,0),
  ('Peixe-espada-branco cru',22.7,6.3,2.9),
  ('Peixe-espada-branco frito',20.2,4.7,0),
  ('Peixe-espada-branco grelhado',15.7,2.8,0),
  ('Peixe-espada-preto cru',24.2,16.6,3.2),
  ('Peixe-espada-preto frito',20.5,3.2,0),
  ('Peixe-espada-preto grelhado',4,1.4,14.9),
  ('Peixinhos da horta',1.4,0.6,1.7),
  ('Pepino cru',0.3,0.4,9.4),
  ('Pera (5 variedades)',0.2,0.3,28.9),
  ('Pera conserva em calda de açúcar',0.3,0.4,14.5),
  ('Pera cozida com açúcar',0.3,0.4,7.8),
  ('Pera cozida sem açúcar',0.2,0.1,69.8),
  ('Pera cristalizada',1.9,2.6,59.9),
  ('Pera desidratada',13.6,0.5,0),
  ('Percebes crus',23,1.3,0),
  ('Perdiz crua',24.7,11.4,0.7),
  ('Perdiz estufada com margarina',21.9,7.6,0.4),
  ('Perna de borrego no forno',21.7,10,0.2),
  ('Perna de cabrito assada com azeite e margarina',21.7,10,0.2),
  ('Perna de cabrito assada com óleo alimentar e margarina',24.3,4.2,0),
  ('Perna de cabrito assada, sem molho',19.3,4,0),
  ('Perna de cabrito crua',24.3,20.9,0),
  ('Perna de carneiro gorda, assada, sem molho',19.1,22.2,0),
  ('Perna de carneiro gorda, crua',26.5,25.9,0),
  ('Perna de carneiro gorda, estufada sem molho',23.5,16.4,0),
  ('Perna de carneiro magra assada com azeite e margarina',23.5,15.3,0),
  ('Perna de carneiro magra assada com margarina',24.2,9,0),
  ('Perna de carneiro magra, assada, sem molho',19.8,5.6,0),
  ('Perna de carneiro magra, crua',17.4,13.4,1.7),
  ('Perna de carneiro magra, estufada com azeite e margarina',17.4,12.5,1.7),
  ('Perna de carneiro magra, estufada com margarina',25.6,10.3,0),
  ('Perna de carneiro magra, estufada sem molho',31.5,2.3,0),
  ('Perna de frango sem pele, cozida',22,2.6,0),
  ('Perna de frango sem pele, crua',19.1,4.4,1.6),
  ('Perna de frango sem pele, estufada com azeite e margarina',19.1,4.1,1.6),
  ('Perna de frango sem pele, estufada com margarina',32.9,5.4,0),
  ('Perna de frango sem pele, estufada sem molho',24.4,12.5,0),
  ('Perna de peru com pele, assada com margarina',18.9,8.1,0),
  ('Perna de peru com pele, crua',19.1,9.7,1.3),
  ('Perna de peru com pele, estufada com margarina',22.4,28.2,0.2),
  ('Perna de porco gorda assada com azeite e margarina',22.4,27.6,0.2),
  ('Perna de porco gorda assada com margarina',22.4,28.2,0.2),
  ('Perna de porco gorda assada com óleo alimentar e margarina',27.6,19.2,0),
  ('Perna de porco gorda assada, sem molho',18.1,18.5,0),
  ('Perna de porco gorda crua',25.5,20.6,0),
  ('Perna de porco gorda grelhada',26,14.6,0.2),
  ('Perna de porco magra assada com azeite e margarina',26,14,0.2),
  ('Perna de porco magra assada com margarina',26,14.5,0.2),
  ('Perna de porco magra assada com óleo alimentar e margarina',31,9.9,0),
  ('Perna de porco magra assada, sem molho',21,7.5,0),
  ('Perna de porco magra crua',22.4,11.9,0.7),
  ('Perna de porco magra estufada com azeite e banha',22.4,11.6,0.7),
  ('Perna de porco magra estufada com azeite e margarina',22.4,11.1,0.7),
  ('Perna de porco magra estufada com margarina',22.4,11.9,0.7),
  ('Perna de porco magra estufada com óleo alimentar e banha',28.6,11,0),
  ('Perna de porco magra estufada, sem molho',27.5,11.7,0),
  ('Perna de porco magra grelhada',20.5,6.1,0),
  ('Peru inteiro com pele, cru',19.2,3.6,0),
  ('Pescada cozida (valor médio)',17.6,1.4,0),
  ('Pescada crua (valor médio)',18.9,3.8,0),
  ('Pescada da África do Sul cozida',17.2,1.3,0),
  ('Pescada da África do Sul crua',23.2,8.4,1.7),
  ('Pescada da África do Sul frita',19.5,3.3,0),
  ('Pescada do Chile cozida',18,1.5,0),
  ('Pescada do Chile crua',20.3,8.8,2.6),
  ('Pescada do Chile frita',20.1,3.7,0),
  ('Pescada europeia cozida',17,0.8,0),
  ('Pescada europeia crua',21.7,7.9,1.4),
  ('Pescada europeia frita',21.7,8.6,2.1),
  ('Pescada frita (valor médio)',0.6,0.3,8.1),
  ('Pêssego (2 variedades)',0.2,0.1,20.6),
  ('Pêssego, conserva em calda de açúcar',21.7,11.9,0),
  ('Picanha grelhada',0.5,0.5,16.5),
  ('Picles de pepino',10.4,2.1,48.3),
  ('Pimenta branca',10.7,2.7,38.3),
  ('Pimenta moída',10.7,3.3,44.5),
  ('Pimenta preta',1.6,0.6,2.7),
  ('Pimento cru',2.7,0.6,3.7),
  ('Pimento grelhado',33.2,51.7,5),
  ('Pinhão, miolo',18,53,12.6),
  ('Pistácio torrado e salgado',18,53,12.6),
  ('Pistácio torrado, sem sal',10.5,10.1,33.2),
  ('Pizza de queijo e tomate',11.7,12.5,29.2),
  ('Pizza de queijo, tomate e fiambre',12,10.6,70.6),
  ('Pó achocolatado com alto teor de gordura',6.5,2.5,86.2),
  ('Pó achocolatado com baixo teor de gordura',22.7,1.3,0),
  ('Polvo cozido sem sal',15.6,1.2,0),
  ('Polvo cru',20.3,16.7,0),
  ('Pombo cru',16.3,1.1,0),
  ('Pota crua',3,2.4,5.9),
  ('Preparado fermentado à base de soja (Vegurte)',25,12.8,0),
  ('Presunto',53,1.4,17.2),
  ('Proteína texturizada de soja',6.1,4.7,44.8),
  ('Pudim de leite e ovos',6.2,4.5,36.3),
  ('Pudim flan caseiro',2,9.4,79.4),
  ('Pudim instantâneo em pó',3.2,1.9,18.3),
  ('Pudim instantâneo preparado com leite magro',3.1,3,18.3),
  ('Pudim instantâneo preparado com leite meio gordo',13.9,5,0.2),
  ('Pulmões de porco, crus',2.3,5.2,16.8),
  ('Puré de batata',7.5,4.7,56.7),
  ('Queijada de queijo fresco',6.7,4.7,55.4),
  ('Queijada de queijo magro',7.2,13.1,40.8),
  ('Queijada de requeijão',18.8,27.3,0),
  ('Queijo Brie',19.2,19.6,0.2),
  ('Queijo Camembert',25.4,34.9,0.1),
  ('Queijo Cheddar',9.3,22,6.9),
  ('Queijo creme para barrar',9.3,22,6.9),
  ('Queijo creme para barrar, alto teor polinsaturados',31.5,25.7,0.2),
  ('Queijo da Ilha',21,25,0.1),
  ('Queijo de Azeitão',26.3,33.5,1.3),
  ('Queijo de Évora',28.9,29.7,0),
  ('Queijo Emmental',28,18.7,0.2),
  ('Queijo flamengo',30,14,0.2),
  ('Queijo flamengo 30% gordura',26,23.4,0.2),
  ('Queijo flamengo 45% gordura',7.3,3.6,11.6),
  ('Queijo fresco açucarado com sabor a fruta',12,13.8,2.1),
  ('Queijo fresco de cabra',19,22.9,0.1),
  ('Queijo fresco de ovelha',13,1.8,5.7),
  ('Queijo fresco meio gordo',22.5,25.7,0.2),
  ('Queijo fundido 40% gordura',25.3,30.6,0),
  ('Queijo Gouda',27.2,33.3,1.4),
  ('Queijo Gruyere',7.6,47,0.3),
  ('Queijo Mascarpone',18.7,19.5,1.3),
  ('Queijo Mozzarella fresco',37.7,27.8,0.1),
  ('Queijo Parmesão',8.4,0.1,10.8),
  ('Queijo Quark açucarado magro com sabor a fruta',10.3,0.3,4),
  ('Queijo Quark natural magro',8.1,8.5,3.9),
  ('Queijo Quark natural meio gordo',25.5,27.8,0.4),
  ('Queijo Raclette',22,31.5,0.2),
  ('Queijo Roquefort',24.8,25.7,0.3),
  ('Queijo Serpa',21,27,0.2),
  ('Queijo Serra da Estrela',25.5,31.5,0.2),
  ('Queijo Serra da Estrela, velho',6.7,18.2,53.8),
  ('Queque',2.8,1,3),
  ('Quiabo cru',12.6,19.1,12.4),
  ('Quiche de espinafres',11.9,22.2,12.9),
  ('Quiche de vegetais',14.4,24.5,23.5),
  ('Quiche lorraine',1.1,0.5,10.9),
  ('Quivi, "Kiwi"',6.1,2.8,60.6),
  ('Quivi, "Kiwi" desidratado',4.7,16.6,31.3),
  ('Rabanada',1,0.2,1.9),
  ('Rabanete cru',6,0.7,10.7),
  ('Rábano cru',14.1,0.2,0),
  ('Raia crua',5.1,3.9,6.5),
  ('Rancho com carne de galinha, porco e vaca',4.8,6.2,6.8),
  ('Rancho com carne de porco',4,0.7,0.3),
  ('Rebentos de alfalfa crus',3.1,0.3,1),
  ('Rebentos de bambu crus',9.2,3.9,5.8),
  ('Rebentos de soja crus',0.3,0,95),
  ('Rebuçados',10.5,12,4.6),
  ('Requeijão',13,12.7,5.1),
  ('Requeijão 13% de proteína',8,11.3,4.1),
  ('Requeijão 8% de proteína',16.2,3,0),
  ('Rim de carneiro, cru',22.3,12.9,0),
  ('Rim de carneiro, frito com margarina',17,3,0),
  ('Rim de porco, cru',23.6,12.4,0),
  ('Rim de porco, frito com margarina',18,2.2,0),
  ('Rim de vaca, cru',7.3,13.4,31.8),
  ('Rissol',6.1,8.6,26.6),
  ('Rissol de camarão',7.3,14.1,19.8),
  ('Rissol de carne com manteiga',7.3,13.9,19.7),
  ('Rissol de carne com margarina',20.4,11.8,0.6),
  ('Robalo assado com cebola, azeite, banha e manteiga',21,10.9,0),
  ('Robalo cozido',18.5,3.5,0),
  ('Robalo cru',23,13,0),
  ('Robalo grelhado',14.9,19,0.8),
  ('Rojões de carne gorda',11.1,5.6,8.7),
  ('Rojões de carne magra',0.4,0.4,12),
  ('Romã',2.6,0.7,2.2),
  ('Rúcula crua',17.7,4.2,0),
  ('Safio cru',0,0,0),
  ('Sal',1.1,1.4,2.6),
  ('Salada de alface e tomate temperada com azeite e vinagre',6.9,4.3,8.4),
  ('Salada de atum',8.7,4.9,7.6),
  ('Salada de bacalhau com grão',1.4,9.3,5.6),
  ('Salada russa',19.5,37.6,1.3),
  ('Salame',20.7,21.1,0),
  ('Salmão cru',23.8,23.7,0),
  ('Salmonete cru',20.5,36.7,0),
  ('Salpicão',3.1,0,0.4),
  ('Salsa fresca',15.8,7,14.5),
  ('Salsa seca',13.5,20.9,0.6),
  ('Salsicha de soja',15.5,16.4,0),
  ('Salsicha fresca crua',7.2,11.6,1.1),
  ('Salsicha fresca estufada com couve e azeite',5.9,8.9,3.7),
  ('Salsicha fresca estufada com legumes e azeite',9,14.7,2.4),
  ('Salsicha tipo Frankfurt',10.2,16.5,2.8),
  ('Salsicha tipo Frankfurt frita (escorrido o óleo) sem adição de sal',12,16.7,3.2),
  ('Salsicha tipo Frankfurt grelhada sem adição de sal',16.6,0.4,0.4),
  ('Sangue de porco, cru',19.5,2.9,0),
  ('Sapateira crua',19.7,10.6,0),
  ('Sarda cozida',19,11.7,0),
  ('Sarda crua',22.5,11.2,0),
  ('Sarda grelhada',22.5,19.4,8.7),
  ('Sardinha frita',18.4,16.4,0),
  ('Sardinha gorda crua',23,15.6,3.5),
  ('Sardinha gorda frita',25,12.3,0),
  ('Sardinha gorda grelhada',22,9.6,0),
  ('Sardinha meio gorda conserva em água, sem espinha e sem pele',24,12,0),
  ('Sardinha meio gorda conserva em azeite',26.3,9,0),
  ('Sardinha meio gorda conserva em azeite (escorrido)',18.9,9.1,0),
  ('Sardinha meio gorda crua',20,10.2,0.5),
  ('Sardinha meio gorda frita',25.9,7.2,0),
  ('Sardinha meio gorda grelhada',25,1.7,5.4),
  ('Sementes de abóbora',29.5,27.9,2.4),
  ('Sementes de cânhamo secas',14.4,34.4,4.6),
  ('Sementes de chia',12.4,17.8,16.2),
  ('Sementes de coentro',19.8,47.5,17),
  ('Sementes de girassol',25,31,18.1),
  ('Sementes de linhaça cruas',28.5,47.7,9),
  ('Sementes de melão',25.5,28.8,15.9),
  ('Sementes de mostarda',19.3,45.9,13.7),
  ('Sementes de papoila',22.1,55,6.4),
  ('Sementes de sésamo',8.8,1.1,73.8),
  ('Sêmola de milho',0,97.5,0),
  ('Shortening para pastelaria',0,100,0),
  ('Shortening para restaurante',0,0,2.3),
  ('Sidra (vinho de maçã)',3.5,1.8,15.8),
  ('Sobremesa à base de soja',12.5,7.5,5.6),
  ('Soja cozida sem sal',44,2.6,21.8),
  ('Soja, farinha com baixo teor de gordura',32.8,19.3,18.3),
  ('Soja, grão seco, cru',19,1.6,0),
  ('Solha crua',23,2,8.9),
  ('Solha frita',21.9,1.8,0),
  ('Solha grelhada',8.7,26.2,29.2),
  ('Sonhos',1.2,1.5,7.6),
  ('Sopa à lavrador',1.3,1.7,5.3),
  ('Sopa, caldo verde',2,0.9,5.8),
  ('Sopa, canja de galinha',0.6,1.4,4.4),
  ('Sopa, creme de cenoura',0.6,1.5,4),
  ('Sopa de abóbora',1,1.6,4.2),
  ('Sopa de agrião',1.3,0.5,5.3),
  ('Sopa de agrião com leite',1.1,1.6,2),
  ('Sopa de agrião com requeijão',4,0.9,7.3),
  ('Sopa de carne de porco',0.8,1.5,5.4),
  ('Sopa de cebola',0.9,0.6,4.4),
  ('Sopa de cenoura',0.8,1.5,5.4),
  ('Sopa de couve-branca',0.9,1.5,5.3),
  ('Sopa de couve-lombarda',2.6,1.4,2.9),
  ('Sopa de cozido',1.6,1.5,6.4),
  ('Sopa de ervilhas',1,1.6,4.8),
  ('Sopa de espinafres',2.5,6.9,4.7),
  ('Sopa de espinafres com ovos',1.8,1.5,6.4),
  ('Sopa de favas',2.5,2.1,4.1),
  ('Sopa de feijão',2.5,1.3,4.9),
  ('Sopa de feijão-branco com couve-portuguesa',1.2,0.4,8.7),
  ('Sopa de feijão-manteiga',2.1,1.8,3.5),
  ('Sopa de feijão-manteiga com couve-lombarda',0.7,1.5,3.5),
  ('Sopa de feijão-verde',0.9,1.5,5.8),
  ('Sopa de feijão-verde e cenoura',0.7,1.9,3.4),
  ('Sopa de feijão-verde e nabo',4.7,2.3,15.1),
  ('Sopa de grão à moda da avó',2.1,1.3,5.3),
  ('Sopa de grão com arroz, espinafres e coentros',2.4,2.1,7),
  ('Sopa de grão com espinafres',2.6,2.3,5.1),
  ('Sopa de grão com espinafres sem arroz',1,1.2,5.8),
  ('Sopa de nabiças (ou de grelos de nabo)',1.3,0.6,1.3),
  ('Sopa de peixe',2.8,1.1,5.8),
  ('Sopa de peixe com massa',1.1,0.8,4.4),
  ('Sopa de tomate',0.8,0.2,1.2),
  ('Sopa de vegetais',0.9,0.9,4.3),
  ('Sopa juliana',1.6,1.6,4.5),
  ('Sopa, puré de feijão',1,1.5,5.5),
  ('Sopa, puré de vegetais',5,3.4,81),
  ('Sucedâneo de café (pó) (2 marcas)',6.5,2.8,77),
  ('Sucedâneo de café (pó) com 20% de café',2.7,0.4,69.4),
  ('Sultanas',0.2,0.1,9.5),
  ('Sumo de ananás, 100%',0,0,64.7),
  ('Sumo de ananás, concentrado',0.3,0.1,9.5),
  ('Sumo de laranja, 100%',0.1,0.7,64.9),
  ('Sumo de laranja, concentrado',0.3,0,1.5),
  ('Sumo de limão, fresco (espremido)',0.1,0.1,9.9),
  ('Sumo de maçã, 100%',0.2,0.1,11.5),
  ('Sumo de pêssego, 100%',1.1,0,3.5),
  ('Sumo de tomate, 100%',18.5,58.9,0.9),
  ('Tahini',1.2,0.1,33.2),
  ('Tâmara fresca',2.5,0.3,67.3),
  ('Tâmara seca',2,0.3,0),
  ('Tamarilho sem pele',2.3,0.3,54.9),
  ('Tamarindo cru',17.9,0.2,0),
  ('Tamboril cru',21.4,0.3,0),
  ('Tamboril grelhado',0.7,0.1,7.8),
  ('Tângera',0.7,0.1,8.7),
  ('Tangerina',0.3,0.2,87.5),
  ('Tapioca',1.8,8,29.3),
  ('Tarte de maçã',4.4,6.2,36.7),
  ('Tarte de maçã e pêssego',0,0,0.2),
  ('Tisana, infusão de ervas',8.7,7.6,1.1),
  ('Tofu frito com azeite',8.7,7.6,1.1),
  ('Tofu frito com óleo de milho',8.5,4.4,0.7),
  ('Tofu simples',1,0.8,4),
  ('Tomate cherry cru',3.7,0.3,14.3),
  ('Tomate concentrado',0.8,0.3,3.5),
  ('Tomate cru',1,0.3,3.2),
  ('Tomate em conserva ao natural',1.5,1.2,7.4),
  ('Tomilho fresco',9.1,7.4,45.3),
  ('Tomilho seco',0.9,0.1,6),
  ('Toranja',8,23.9,29.6),
  ('Torta de chocolate e chantilly',12.5,4.2,69.7),
  ('Tosta de trigo',15.4,5.1,62.6),
  ('Tosta de trigo integral',11.3,3.8,72.7),
  ('Tosta de trigo sem sal',11.3,3.8,72.7),
  ('Tosta de trigo simples',8.4,72,0),
  ('Toucinho de porco entremeado fresco, cru',16.1,67.9,0),
  ('Toucinho de porco entremeado fresco, grelhado sem adição de sal',16.7,33.9,0),
  ('Toucinho de porco entremeado ligeiramente salgado, cozido sem adição de sal',13.7,50.1,0),
  ('Toucinho de porco entremeado ligeiramente salgado, cru',17.4,29.1,0.5),
  ('Toucinho de porco entremeado magro',16.4,2.4,7.2),
  ('Tremoço, cozido e salgado',16,2.4,7.2),
  ('Tremoço cozido, sem sal',12.4,2.5,61.3),
  ('Trigo Sarraceno (grão) cru',7.6,16.6,0),
  ('Tripa de porco fresca',16.3,10.5,0.1),
  ('Tripa de vaca crua',17.8,2.3,0),
  ('Truta arco-íris crua',21.3,3.7,0),
  ('Truta arco-íris grelhada',3.3,0.3,14.5),
  ('Túbera (trufa) crua',0.3,0.5,17.3),
  ('Uva branca (5 variedades)',0.3,0.5,18),
  ('Uva (média, branca e tinta)',1.8,0.7,67),
  ('Uva seca (passas)',0.3,0.5,18.6),
  ('Uva tinta (5 variedades)',24.2,20.4,0),
  ('Vaca assada',24.2,20.4,0),
  ('Vaca assada com azeite e margarina',24.2,19.6,0),
  ('Vaca assada com margarina',24.2,20.4,0),
  ('Vaca assada com óleo alimentar e margarina',26.9,9.4,0),
  ('Vaca assada, sem molho',33.7,13.8,0),
  ('Vaca magra cozida',21.8,14.2,1.2),
  ('Vaca magra estufada',5.5,4.4,11.4),
  ('Vaca magra estufada à jardineira',21.8,14.2,1.2),
  ('Vaca magra estufada com azeite e margarina',21.8,13.6,1.2),
  ('Vaca magra estufada com margarina',21.8,14.2,1.2),
  ('Vaca magra estufada com óleo alimentar e margarina',31.5,12,0),
  ('Vaca magra estufada, sem molho',21.4,20.2,1.2),
  ('Vaca meio gorda estufada',21.4,20.2,1.2),
  ('Vaca meio gorda estufada com azeite e margarina',21.4,19.6,1.2),
  ('Vaca meio gorda estufada com margarina',21.4,20.2,1.2),
  ('Vaca meio gorda estufada com óleo alimentar e margarina',31.8,17,0),
  ('Vaca meio gorda estufada, sem molho',19.4,10.7,0),
  ('Vaca para assar crua',21.7,9.8,0),
  ('Vaca para cozer ou estufar magra crua',21.3,15.8,0),
  ('Vaca para cozer ou estufar meio gorda crua',20.6,3.3,0),
  ('Veado cru',18.5,1,0),
  ('Vieira, crua',0.3,0,0.6),
  ('Vinagre',0.1,0,12),
  ('Vinho espumante doce',0.1,0,0.1),
  ('Vinho espumante extra bruto',0.1,0,4.2),
  ('Vinho espumante meio Seco',0.1,0,2.6),
  ('Vinho espumante seco',0.2,0,9),
  ('Vinho generoso da Madeira',0.1,0,14),
  ('Vinho generoso do Porto, doce',0.1,0,6.5),
  ('Vinho generoso do Porto, meio seco',0.1,0,4),
  ('Vinho generoso do Porto, seco',0.1,0,1.2),
  ('Vinho maduro branco',0.1,0,0.1),
  ('Vinho maduro palhete',0.1,0,0.2),
  ('Vinho maduro tinto',0.2,0,2.4),
  ('Vinho rosé',0,0,0.1),
  ('Vinho verde branco',0,0,0.3),
  ('Vinho verde tinto',4.8,0.6,15.8);

-- Outras quantidades/unidades.
insert into gfit.foods (name, base_qty, unit, protein_g, fat_g, carb_g) values
  ('mozzarella light (125g)',125,'g',25.6,10.6,1),
  ('Ovo UNID.',1,'unid',5.8,5.2,0.5),
  ('mozzarella (125g)',125,'g',18,19,2),
  ('maça/pera UNID.',1,'unid',1.4,0.2,17.7),
  ('banana UNID.',1,'unid',1.9,0.5,26.2),
  ('abacate UNID.',1,'unid',2.4,18.4,10.8),
  ('gema ovo UNID.',1,'unid',3,5,1),
  ('xtreme mass gainer',1,'unid',12,1,50);
