-- GFit — músculos e biblioteca de exercícios.
-- Gerado por scripts/extract_excel.py a partir de FG_Planilha.xlsx.

insert into gfit.muscles (slug, name, sort_order) values
  ('abs','Abs',0),
  ('biceps','Biceps',10),
  ('dorsal','Dorsal',20),
  ('ombro_frontal','Ombro frontal',30),
  ('ombro_medio','Ombro médio',40),
  ('ombro_posterior','Ombro posterior',50),
  ('peito','Peito',60),
  ('trapezio','Trapézio',70),
  ('triceps','Triceps',80),
  ('quadriceps','Quadriceps',90),
  ('posterior_de_coxa','Posterior de coxa',100),
  ('gluteo','Glúteo',110),
  ('lombares','Lombares',120),
  ('gemeos','Gémeos',130),
  ('adutores','Adutores',140)
on conflict (slug) do nothing;

-- Os músculos viajam como 'slug:peso|slug:peso' e viram jsonb à chegada.
insert into gfit.exercises
  (name, pattern, category, video_url, primary_muscle, muscles, equipment)
select d.name, d.pattern, d.category, d.video_url,
       nullif(split_part(split_part(d.m, '|', 1), ':', 1), ''),
       coalesce((
         select jsonb_agg(jsonb_build_object(
                  'muscle', split_part(part, ':', 1),
                  'weight', split_part(part, ':', 2)::numeric))
           from unnest(string_to_array(d.m, '|')) part
          where part <> ''
       ), '[]'::jsonb),
       d.equipment
from (values
  ('Biceps crul halteres deitado','Puxar','Biceps curl','https://youtu.be/WcUsU8gNmGI','biceps:1','Halteres'),
  ('Biceps crul barra pé direita','Puxar','Biceps curl','https://youtu.be/tPIZtS0j1Hg','biceps:1','Barra'),
  ('Biceps crul barra pé Z','Puxar','Biceps curl',null,'biceps:1','Barra'),
  ('Biceps curl banco inclinado halteres','Puxar','Biceps curl','https://youtu.be/9JbUuix8X4o','biceps:1','Halteres'),
  ('Biceps curl cristo cabos','Puxar','Biceps curl','https://youtu.be/1m6fZSun6ME','biceps:1','Cabos'),
  ('Biceps curl concentrado','Puxar','Biceps curl','https://youtube.com/shorts/pXQojCQjmZA?feature=share','biceps:1','Livre'),
  ('Biceps curl elástico','Puxar','Biceps curl','https://youtu.be/n1RomOv6TWw','biceps:1','Elástico'),
  ('Biceps curl maquina scott','Puxar','Biceps curl','https://youtu.be/Kzkeb3Ce_pk','biceps:1','Máquina'),
  ('Biceps curl nos cabos cross','Puxar','Biceps curl','https://youtu.be/orDUcRQnH3k','biceps:1','Cabos'),
  ('Biceps curl pé cabos pronado','Puxar','Biceps curl','https://youtu.be/rzhZ9k73ryA','biceps:1','Cabos'),
  ('Biceps curl pé cabos supinado','Puxar','Biceps curl',null,'biceps:1','Cabos'),
  ('Biceps curl rosca pé','Puxar','Biceps curl','https://youtu.be/Eg9Kwr92gS0','biceps:1','Livre'),
  ('Biceps curl scott unilateral','Puxar','Biceps curl','https://youtu.be/pYMAEfw5HXA','biceps:1','Máquina'),
  ('Biceps curl scott unilateral cabos','Puxar','Biceps curl','https://youtu.be/8LFPPPaYISo','biceps:1','Cabos'),
  ('Biceps martelo pé corda','Puxar','Biceps curl','https://youtu.be/qo92P0K2jb0','biceps:1','Livre'),
  ('Bicesp curl TRX','Puxar','Biceps curl','https://youtu.be/g93I74fnOpk','biceps:1','TRX'),
  ('Alavanca','Puxar','Elevações/puxadas vertical','https://youtu.be/NgrgYoDFPoc','dorsal:1|biceps:0.5|trapezio:0.3','Livre'),
  ('Alavanca unilateral','Puxar','Elevações/puxadas vertical','https://youtu.be/UW2PZRGpAFU','dorsal:1|biceps:0.5|trapezio:0.3','Livre'),
  ('Elevações assistidas','Puxar','Elevações/puxadas vertical','https://youtube.com/shorts/H2V6HlpaEyE?feature=share','dorsal:1|biceps:0.5|trapezio:0.3','Livre'),
  ('Elevações elástico','Puxar','Elevações/puxadas vertical','https://youtu.be/lIJXCLxzZvI','dorsal:1|biceps:0.5|trapezio:0.3','Elástico'),
  ('Elevações negativas','Puxar','Elevações/puxadas vertical','https://youtu.be/381QNvqq_5s','dorsal:1|biceps:0.5|trapezio:0.3','Livre'),
  ('Elevações pega neutra','Puxar','Elevações/puxadas vertical','https://youtu.be/x6IKM5FNbzQ','dorsal:1|biceps:0.5|trapezio:0.3','Livre'),
  ('Elevações pega supinada','Puxar','Elevações/puxadas vertical',null,'dorsal:1|biceps:0.5|trapezio:0.3','Livre'),
  ('Elevações pronadas','Puxar','Elevações/puxadas vertical','https://youtu.be/Gadiybic1jk','dorsal:1|biceps:0.5|trapezio:0.3','Livre'),
  ('Puxador dorsal unilateral no banco','Puxar','Elevações/puxadas vertical','https://youtube.com/shorts/uc1H5C-tpEU?feature=share','dorsal:1|biceps:0.5|trapezio:0.3','Banco'),
  ('Puxada vertical elástico','Puxar','Elevações/puxadas vertical','https://youtu.be/WvehBL6yQnE','dorsal:1|biceps:0.5|trapezio:0.3','Elástico'),
  ('Puxada vertical TRX','Puxar','Elevações/puxadas vertical','https://youtu.be/gEfc9YVoySs','dorsal:1|biceps:0.5|trapezio:0.3','TRX'),
  ('Puxador vertical dorsal neutra','Puxar','Elevações/puxadas vertical','https://youtu.be/dY6KGH9LsbI','dorsal:1|biceps:0.5|trapezio:0.3','Livre'),
  ('Puxador vertical dorsal pronado','Puxar','Elevações/puxadas vertical','https://youtu.be/kF3nRuX99rw','dorsal:1|biceps:0.5|trapezio:0.3','Livre'),
  ('Puxador vertical dorsal supinado','Puxar','Elevações/puxadas vertical',null,'dorsal:1|biceps:0.5|trapezio:0.3','Livre'),
  ('Puxador vertical unilateral cruzado','Puxar','Elevações/puxadas vertical','https://youtube.com/shorts/A9Eqjm4W9_g?feature=share','dorsal:1|biceps:0.5|trapezio:0.3','Livre'),
  ('Puxador vertical inclinado no banco','Puxar','Elevações/puxadas vertical','https://youtu.be/ZUt7vr8tZb0','dorsal:1|biceps:0.5|trapezio:0.3','Banco'),
  ('Puxador vertical cruzada unilateral joelhos','Puxar','Elevações/puxadas vertical','https://youtu.be/-tH0kO5CgWk','dorsal:1|biceps:0.5|trapezio:0.3','Livre'),
  ('Pull face cabos pé','Puxar','Pull Faces','https://youtu.be/EvaEXreIYEU','ombro_posterior:1|trapezio:1|ombro_medio:0.5|biceps:0.3','Cabos'),
  ('Pull face cabos sentado','Puxar','Pull Faces','https://youtu.be/lrmgEHkHfNU','ombro_posterior:1|trapezio:1|ombro_medio:0.5|biceps:0.3','Cabos'),
  ('Pull face TRX','Puxar','Pull Faces','https://youtu.be/zoM5p9QCslY','ombro_posterior:1|trapezio:1|ombro_medio:0.5|biceps:0.3','TRX'),
  ('Pull over cabos em pé','Puxar','Pull over Cabos','https://youtu.be/F8kzp7ldavg','dorsal:1|trapezio:0.5|triceps:0.3','Cabos'),
  ('Pull over deitado halteres','Puxar','Pull over Cabos','https://youtube.com/shorts/KgvssqlufQM?feature=share','dorsal:1|trapezio:0.5|triceps:0.3','Halteres'),
  ('Pull over deslizante','Puxar','Pull over Cabos','https://youtu.be/fPXRvw6LmJI','dorsal:1|trapezio:0.5|triceps:0.3','Livre'),
  ('Remada aberta sentado cabos','Puxar','Remada aberta','https://youtube.com/shorts/wo1rfNoCgTQ?feature=share','ombro_posterior:1|trapezio:1|lombares:0.5|biceps:0.3','Cabos'),
  ('Remada aberta apoio banco','Puxar','Remada aberta','https://youtu.be/NZaNK2IIGts','ombro_posterior:1|trapezio:1|biceps:0.3','Banco'),
  ('Remada aberta pé elastico','Puxar','Remada aberta','https://youtu.be/cbrbksVsuQ4','ombro_posterior:1|trapezio:1|lombares:0.5|biceps:0.3','Elástico'),
  ('Remada aberta TRX','Puxar','Remada aberta','https://youtu.be/oEjRAgKCUwc','ombro_posterior:1|trapezio:1|lombares:0.5|biceps:0.3','TRX'),
  ('Remada alta barra','Puxar','Remada aberta','https://youtu.be/EwfwfhTPhe0','ombro_medio:1|ombro_posterior:1|trapezio:0.5|biceps:0.3','Barra'),
  ('Remada alta cabos','Puxar','Remada aberta',null,'ombro_medio:1|ombro_posterior:1|trapezio:0.5|biceps:0.3','Cabos'),
  ('Remada alta halteres','Puxar','Remada aberta',null,'ombro_medio:1|ombro_posterior:1|trapezio:0.5|biceps:0.3','Halteres'),
  ('Remada aberta banco inclinado halteres','Puxar','Remada aberta','https://youtube.com/shorts/jQIwRsyq3Yc?feature=share','ombro_posterior:1|trapezio:1|biceps:0.3','Halteres'),
  ('Remada curva encosto aberta','Puxar','Remada aberta','https://youtu.be/qwNF1WDCfI4','ombro_posterior:1|trapezio:1|dorsal:0.5|biceps:0.3','Livre'),
  ('Remada sentado nos cabos pronado','Puxar','Remada aberta','https://youtu.be/xXh1dFX60cs','ombro_posterior:1|trapezio:1|dorsal:0.5|lombares:0.5|biceps:0.3','Cabos'),
  ('Remada baixa barra pronada','Puxar','Remada aberta','https://youtu.be/CoUt2wXKquA','ombro_posterior:1|trapezio:1|dorsal:0.5|lombares:0.5|biceps:0.3','Barra'),
  ('Remada baixa barra supinada','Puxar','Remada fechada','https://youtu.be/1Hj4DtaPADE','dorsal:1|trapezio:1|lombares:0.5|ombro_posterior:0.5|biceps:0.3','Barra'),
  ('Remada baixa barra supinada apoio banco','Puxar','Remada fechada','https://youtu.be/QwWFTQPGHSY','dorsal:1|trapezio:1|ombro_posterior:0.5|biceps:0.3','Barra'),
  ('Remada baixa halteres apoio banco','Puxar','Remada fechada','https://youtube.com/shorts/eJ0MLjjbbjk?feature=share','dorsal:1|trapezio:1|ombro_posterior:0.5|biceps:0.3','Halteres'),
  ('Remada baixa halteres neutro','Puxar','Remada fechada','https://youtube.com/shorts/IZRQMn9rc0o?feature=share','dorsal:1|trapezio:1|lombares:0.5|ombro_posterior:0.5|biceps:0.3','Halteres'),
  ('Remada baixa mochila','Puxar','Remada fechada','https://youtu.be/GUS7wdRfRNk','dorsal:1|trapezio:1|lombares:0.5|ombro_posterior:0.5|biceps:0.3','Livre'),
  ('Remada banco inclinado halteres','Puxar','Remada fechada','https://youtu.be/VOgtP6qh9Ws','dorsal:1|trapezio:1|ombro_posterior:0.5|biceps:0.3','Halteres'),
  ('Remada curva encosto fechada','Puxar','Remada fechada','https://youtube.com/shorts/Pt6-1kTAfE0?feature=share','dorsal:1|trapezio:1|ombro_posterior:0.5|biceps:0.3','Livre'),
  ('Remada deitado banco barra pronado','Puxar','Remada fechada','https://youtu.be/BAEmJXvZd5E','dorsal:1|trapezio:1|ombro_posterior:0.5|biceps:0.3','Barra'),
  ('Remada deitado halteres','Puxar','Remada fechada','https://youtu.be/ykHSVgXU1Yg','dorsal:1|trapezio:1|ombro_posterior:0.5|biceps:0.3','Halteres'),
  ('Remada deitado na mesa','Puxar','Remada fechada','https://youtu.be/x99pS7PgAAQ','dorsal:1|trapezio:1|lombares:0.5|ombro_posterior:0.5|biceps:0.3','Livre'),
  ('Remada fechada pé elastico','Puxar','Remada fechada','https://youtu.be/RiHWKt7uK0U','dorsal:1|trapezio:1|lombares:0.5|ombro_posterior:0.5|biceps:0.3','Elástico'),
  ('Remada fechada TRX','Puxar','Remada fechada','https://youtu.be/iu2vnAvS8SA','dorsal:1|trapezio:1|lombares:0.5|ombro_posterior:0.5|biceps:0.3','TRX'),
  ('Remada inclinado na maquina com encosto','Puxar','Remada fechada','https://youtube.com/shorts/6Os0Lm8OWAM?feature=share','dorsal:1|trapezio:1|ombro_posterior:0.5|biceps:0.3','Máquina'),
  ('Remada maquina encosto neutra','Puxar','Remada fechada','https://youtu.be/NmqklJDizWo','dorsal:1|trapezio:1|ombro_posterior:0.5|biceps:0.3','Máquina'),
  ('Remada sentado nos cabos pega neutra','Puxar','Remada fechada','https://youtu.be/pss0QOfpSao','dorsal:1|trapezio:1|lombares:0.5|ombro_posterior:0.5|biceps:0.3','Cabos'),
  ('Remada sentado nos cabos supinado','Puxar','Remada fechada',null,'dorsal:1|trapezio:1|lombares:0.5|ombro_posterior:0.5|biceps:0.3','Cabos'),
  ('Remada T','Puxar','Remada fechada','https://youtu.be/ktdUTtnfhWI','dorsal:1|trapezio:1|lombares:0.5|ombro_posterior:0.5|biceps:0.3','Livre'),
  ('Remada unilateral cabos','Puxar','Remada fechada','https://youtu.be/I2CQeB4LrAw','dorsal:1|trapezio:1|lombares:0.5|ombro_posterior:0.5|biceps:0.3','Cabos'),
  ('Remada unilateral halteres','Puxar','Remada fechada','https://youtu.be/b5Aqknu-1Ng','dorsal:1|trapezio:1|lombares:0.5|ombro_posterior:0.5|biceps:0.3','Halteres'),
  ('Remada unilateral mochila','Puxar','Remada fechada','https://youtu.be/WyVuZ5uK8k8','dorsal:1|trapezio:1|lombares:0.5|ombro_posterior:0.5|biceps:0.3','Livre'),
  ('Encolhimentos barra','Puxar','Trapézio',null,'trapezio:1','Barra'),
  ('Encolhimentos halteres','Puxar','Trapézio',null,'trapezio:1','Halteres'),
  ('Encolhimentos smith machine','Puxar','Trapézio',null,'trapezio:1','Barra'),
  ('Y comboio','Puxar','Voos',null,'trapezio:1|ombro_posterior:1|ombro_medio:0.5','Livre'),
  ('Voos banco inclinado halteres','Puxar','Voos','https://youtu.be/aG3nDTjm16Y','ombro_posterior:1|trapezio:1|ombro_medio:0.5','Halteres'),
  ('Voos inclinado com halteres','Puxar','Voos',null,'ombro_posterior:1|trapezio:1|ombro_medio:0.5','Halteres'),
  ('Voos máquina','Puxar','Voos','https://youtu.be/MKfzpZ4Q0uU','ombro_posterior:1|trapezio:1|ombro_medio:0.5','Máquina'),
  ('Voos pé cabos','Puxar','Voos','https://youtu.be/4yYz0NCWFRk','ombro_posterior:1|trapezio:1|ombro_medio:0.5','Cabos'),
  ('Voos sentado halteres','Puxar','Voos','https://youtu.be/Ft7E49Tw3UQ','ombro_posterior:1|trapezio:1|ombro_medio:0.5','Halteres'),
  ('Voos TRX','Puxar','Voos','https://youtube.com/shorts/uhiztQ8V9Vw?feature=share','ombro_posterior:1|trapezio:1|ombro_medio:0.5','TRX'),
  ('Abdutores deitado','Perna','Abdutores','https://youtu.be/FA6jHdFlvg8','gluteo:1','Livre'),
  ('Abdutores máquina','Perna','Abdutores','https://youtu.be/oHjivORRk1Y','gluteo:1','Máquina'),
  ('Abdutores pêndulo','Perna','Abdutores',null,'gluteo:1','Livre'),
  ('Adutores deitado','Perna','Adutores','https://youtu.be/teGAg19KWw0','adutores:1','Livre'),
  ('Adutores máquina','Perna','Adutores',null,'adutores:1','Máquina'),
  ('Adutores pêndulo','Perna','Adutores',null,'adutores:1','Livre'),
  ('Agachamento TRX','Perna','Agachamento','https://www.youtube.com/shorts/GHar7RpOJrg','quadriceps:1|gluteo:1|adutores:0.5|posterior_de_coxa:0.5|gemeos:0.3','TRX'),
  ('Agachamento cadeira','Perna','Agachamento','https://www.youtube.com/shorts/a7VXjG3LvR8','quadriceps:1|gluteo:1|adutores:0.5|posterior_de_coxa:0.5|gemeos:0.3','Livre'),
  ('Agachamento 1 perna cadeira','Perna','Agachamento','https://youtu.be/MOmHtKUKbvo','quadriceps:1|gluteo:1|adutores:0.5|posterior_de_coxa:0.5|gemeos:0.3','Livre'),
  ('Agachamento barra','Perna','Agachamento','https://youtu.be/x8hljkfvgo4','quadriceps:1|gluteo:1|adutores:0.5|gemeos:0.5|posterior_de_coxa:0.3','Barra'),
  ('Agachamento normal smith','Perna','Agachamento','https://youtube.com/shorts/sNTHP1a9byE?feature=share','quadriceps:1|gluteo:1|adutores:0.5|gemeos:0.5|posterior_de_coxa:0.3','Barra'),
  ('Agachamento curto em baixo','Perna','Agachamento','https://youtu.be/9hZT-XcdPqc','quadriceps:1|gluteo:1|adutores:0.5|gemeos:0.5|posterior_de_coxa:0.3','Livre'),
  ('Agachamento mochila','Perna','Agachamento','https://youtu.be/u53nsBJnQRM','quadriceps:1|gluteo:1|adutores:0.5|gemeos:0.5|posterior_de_coxa:0.3','Livre'),
  ('Pistol squat','Perna','Agachamento','https://youtu.be/RbQZwsGUAzY','quadriceps:1|gluteo:1|adutores:0.5|posterior_de_coxa:0.5|gemeos:0.3','Livre'),
  ('Pistol squat TRX','Perna','Agachamento','https://youtu.be/SH5ivwB_LhE','quadriceps:1|gluteo:1|adutores:0.5|posterior_de_coxa:0.5|gemeos:0.3','TRX'),
  ('Gémeos no leg press','Perna','Gémeos',null,'gemeos:1','Máquina'),
  ('Gemeos pé maquina','Perna','Gémeos','https://youtu.be/SYPJv6TPACY','gemeos:1','Máquina'),
  ('Gémeos pé peso corpo','Perna','Gémeos','https://youtu.be/6ZwbBza7x54','gemeos:1','Livre'),
  ('Solear','Perna','Gémeos',null,'gemeos:1','Livre'),
  ('Glúteos kick máquina','Perna','Glúteo máquina kick, cabos','https://youtu.be/Lk9DA7MxiwY','gluteo:1|posterior_de_coxa:0.5|adutores:0.3','Máquina'),
  ('Glúteo pé cabos','Perna','Glúteo máquina kick, cabos',null,'gluteo:1|posterior_de_coxa:1|adutores:0.3','Cabos'),
  ('Glúteos kick solo banda','Perna','Glúteo máquina kick, cabos','https://youtu.be/u4IpIy0VGjE','gluteo:1|posterior_de_coxa:0.5|adutores:0.3','Elástico'),
  ('Glúteos pêndulo','Perna','Glúteo máquina kick, cabos','https://youtu.be/u4IpIy0VGjE','gluteo:1|posterior_de_coxa:1|adutores:0.3','Livre'),
  ('Agachamento com pés avançados smith','Perna','Hack Squat','https://youtu.be/-b2FHDcuefw','quadriceps:1|gluteo:0.5|adutores:0.5|gemeos:0.3','Barra'),
  ('Agachamento frontal barra','Perna','Hack Squat','https://youtu.be/sN5b_esSVj4','quadriceps:1|gluteo:1|posterior_de_coxa:0.5|adutores:0.5|gemeos:0.3','Barra'),
  ('Agachamento frontal TRX','Perna','Hack Squat','https://youtu.be/wzmCYDapfm8','quadriceps:1|gluteo:0.5|adutores:0.5|gemeos:0.3','TRX'),
  ('Agachamento hack na porta','Perna','Hack Squat','https://youtu.be/4JxUq7gfGxw','quadriceps:1|gluteo:0.5|adutores:0.5|gemeos:0.3','Máquina'),
  ('Agchamento com calços','Perna','Hack Squat','https://youtu.be/YyuF67n29-Q','quadriceps:1|gluteo:1|posterior_de_coxa:0.5|adutores:0.5|gemeos:0.3','Livre'),
  ('Hack squat','Perna','Hack Squat','https://youtu.be/eKXpjMUG2H8','quadriceps:1|gluteo:1|posterior_de_coxa:0.5|adutores:0.5|gemeos:0.3','Máquina'),
  ('Hack squat quadríceps','Perna','Hack Squat','https://youtube.com/shorts/bab2a6zkwqI?feature=share','quadriceps:1|gluteo:0.5|adutores:0.5|gemeos:0.3','Máquina'),
  ('Hack squat pêndulo','Perna','Hack Squat','https://youtu.be/zzQHXTpceAo','quadriceps:1|gluteo:1|posterior_de_coxa:0.5|adutores:0.5|gemeos:0.3','Máquina'),
  ('Power squat','Perna','Hack Squat','https://youtu.be/m2dehWkOe-k','quadriceps:1|gluteo:1|posterior_de_coxa:0.5|adutores:0.5|gemeos:0.3','Livre'),
  ('Sissy squat maquina','Perna','Hack Squat','https://youtu.be/iDMXEv8L64Y','quadriceps:1|adutores:0.5|gemeos:0.3','Máquina'),
  ('Sissy squat livre','Perna','Hack Squat','https://youtube.com/shorts/MNHZ7VYL3Ys?feature=share','quadriceps:1|adutores:0.5|gemeos:0.3','Livre'),
  ('Sissy squat smith','Perna','Hack Squat',null,'quadriceps:1|adutores:0.5|gemeos:0.3','Barra'),
  ('Leg crul deitado elástico','Perna','leg curl','https://youtu.be/q26jPaocakg','posterior_de_coxa:1|gemeos:0.5','Elástico'),
  ('Leg crul pé','Perna','leg curl','https://youtu.be/WGsEzHD65HQ','posterior_de_coxa:1|gemeos:0.5','Livre'),
  ('Leg crul sentado máquina','Perna','leg curl','https://youtu.be/7dQ6VBF2gAg','posterior_de_coxa:1|gemeos:0.5','Máquina'),
  ('Leg curl deitado','Perna','leg curl','https://youtu.be/p3982igeDE8','posterior_de_coxa:1|gemeos:0.5','Livre'),
  ('Leg curl deslizante','Perna','leg curl','https://youtu.be/iLNTqSVGyFM','posterior_de_coxa:1|gemeos:0.5','Livre'),
  ('Leg curl trx','Perna','leg curl','https://youtu.be/e2N3xn8kVl4','posterior_de_coxa:1|gemeos:0.5','TRX'),
  ('Leg curl unilateral deitado','Perna','leg curl','https://youtu.be/529K0ZjxJzQ','posterior_de_coxa:1|gemeos:0.5','Livre'),
  ('Nordic curl','Perna','leg curl','https://youtu.be/Z4mFZYLwsQQ','posterior_de_coxa:1|gluteo:0.5','Livre'),
  ('Leg extension','Perna','Leg Extension','https://youtu.be/-6OIaQYvbjw','quadriceps:1','Livre'),
  ('Leg extension unilateral','Perna','Leg Extension','https://youtu.be/BSLiPKdHWsU','quadriceps:1','Livre'),
  ('Leg press 45º glúteo','Perna','Leg Press','https://youtu.be/6DdaG1KsE38','quadriceps:1|gluteo:1|adutores:0.5|posterior_de_coxa:0.5|gemeos:0.3','Máquina'),
  ('Leg press 45º quadríceps','Perna','Leg Press','https://youtube.com/shorts/L-AqifK0ocE?feature=share','quadriceps:1|gluteo:0.5|gemeos:0.5|posterior_de_coxa:0.3','Máquina'),
  ('Leg press horizontal','Perna','Leg Press','https://youtu.be/nC7ByT4l2Rs','quadriceps:1|gluteo:1|adutores:0.5|posterior_de_coxa:0.5|gemeos:0.3','Máquina'),
  ('Bulgarian lunges halteres','Perna','Lunge / step up','https://youtu.be/NI7YGthe4EA','quadriceps:1|gluteo:1|posterior_de_coxa:0.5|adutores:0.5|gemeos:0.3','Halteres'),
  ('Bulgarian lunges smith','Perna','Lunge / step up','https://youtu.be/LZGgiRGTPcQ','quadriceps:1|gluteo:1|posterior_de_coxa:0.5|adutores:0.5|gemeos:0.3','Barra'),
  ('Lunge dois pés no steps','Perna','Lunge / step up','https://youtu.be/1VJWgLoPyLc','quadriceps:1|gluteo:1|posterior_de_coxa:0.5|adutores:0.5|gemeos:0.3','Livre'),
  ('Lunge dois pés no steps na smith','Perna','Lunge / step up','https://youtube.com/shorts/UtbesEEl-_k?feature=share','quadriceps:1|gluteo:1|posterior_de_coxa:0.5|adutores:0.5|gemeos:0.3','Barra'),
  ('Lunge fixo smith','Perna','Lunge / step up',null,'quadriceps:1|gluteo:1|posterior_de_coxa:0.5|adutores:0.5|gemeos:0.3','Barra'),
  ('Lunge fixo quadriceps','Perna','Lunge / step up','https://youtube.com/shorts/_zDJioacERU?feature=share','quadriceps:1|gluteo:0.5|adutores:0.5|gemeos:0.3','Livre'),
  ('Lunge fixo halteres','Perna','Lunge / step up','https://youtu.be/YA2VDHL7eZc','quadriceps:1|gluteo:1|posterior_de_coxa:0.5|adutores:0.5|gemeos:0.3','Halteres'),
  ('Lunge passo a trás halteres','Perna','Lunge / step up','https://youtu.be/RH8ycVbvRE0','quadriceps:1|gluteo:1|posterior_de_coxa:0.5|adutores:0.5|gemeos:0.3','Halteres'),
  ('Lunge passo a trás no step','Perna','Lunge / step up','https://youtu.be/Z6spwKEdb8A','quadriceps:1|gluteo:1|posterior_de_coxa:0.5|adutores:0.5|gemeos:0.3','Livre'),
  ('Lunge pé frente no step smith','Perna','Lunge / step up','https://youtube.com/shorts/RB9SX4KkuEk?feature=share','quadriceps:1|gluteo:1|posterior_de_coxa:0.5|adutores:0.5|gemeos:0.3','Barra'),
  ('Lunge pé frente no step','Perna','Lunge / step up','https://youtu.be/zVgZgk2EbW4','quadriceps:1|gluteo:1|posterior_de_coxa:0.5|adutores:0.5|gemeos:0.3','Livre'),
  ('Lunge pé trás no step','Perna','Lunge / step up',null,'quadriceps:1|gluteo:1|posterior_de_coxa:0.5|adutores:0.5|gemeos:0.3','Livre'),
  ('Passadas barra','Perna','Lunge / step up','https://youtu.be/vzGd1kmixjc','quadriceps:1|gluteo:1|posterior_de_coxa:0.5|adutores:0.5|gemeos:0.3','Barra'),
  ('Passadas halteres','Perna','Lunge / step up',null,'quadriceps:1|gluteo:1|posterior_de_coxa:0.5|adutores:0.5|gemeos:0.3','Halteres'),
  ('Step up','Perna','Lunge / step up','https://youtu.be/Gc4VxWFUXgo','quadriceps:1|gluteo:1|posterior_de_coxa:0.5|adutores:0.5|gemeos:0.3','Livre'),
  ('Step up cadeira','Perna','Lunge / step up','https://youtu.be/CIF_qdeqKgM','quadriceps:1|gluteo:1|posterior_de_coxa:0.5|adutores:0.5|gemeos:0.3','Livre'),
  ('Extensão anca no banco horizontal','Perna','Peso Morto Romeno','https://youtu.be/QijTo6HBLr4','gluteo:1|posterior_de_coxa:1|lombares:0.5','Banco'),
  ('Extensão anca no banco','Perna','Peso Morto Romeno','https://youtu.be/lMsFTJ7TZm4','gluteo:1|posterior_de_coxa:1|lombares:0.5','Banco'),
  ('Peso morto convencional','Perna','Peso Morto Romeno','https://youtu.be/qVt5DoIWoU8','gluteo:1|posterior_de_coxa:1|lombares:0.5','Livre'),
  ('Peso morto romeno com elastico','Perna','Peso Morto Romeno','https://youtube.com/shorts/Fim3vhgdRFk?feature=share','gluteo:1|posterior_de_coxa:1|lombares:0.5','Elástico'),
  ('Peso morto romeno barra','Perna','Peso Morto Romeno','https://youtu.be/e0rnci_VtNY','gluteo:1|posterior_de_coxa:1|lombares:0.5','Barra'),
  ('Peso morto romeno halteres','Perna','Peso Morto Romeno','https://youtube.com/shorts/EJan7nBcJzM?feature=share','gluteo:1|posterior_de_coxa:1|lombares:0.5','Halteres'),
  ('Peso morto romeno unilateral','Perna','Peso Morto Romeno','https://youtube.com/shorts/pcygr8dUaTQ?feature=share','gluteo:1|posterior_de_coxa:1|lombares:0.5|adutores:0.3','Livre'),
  ('Agachamento sumo barra','Perna','peso morto terra/sumo','https://youtu.be/7wvD5fsY8CQ','quadriceps:1|gluteo:1|adutores:0.5|posterior_de_coxa:0.5','Barra'),
  ('Agachamento sumo halteres','Perna','peso morto terra/sumo','https://youtu.be/vJ89YIbLnto','quadriceps:1|gluteo:1|adutores:0.5|posterior_de_coxa:0.5','Halteres'),
  ('Peso morto sumo','Perna','peso morto terra/sumo','https://youtu.be/V24CoFGIKvc','gluteo:1|adutores:1|quadriceps:0.5|posterior_de_coxa:0.5','Livre'),
  ('Ponte Glúteos Chão','Perna','Ponte Glúteos','https://www.youtube.com/shorts/1satDE63Bwc','gluteo:1|posterior_de_coxa:0.5','Livre'),
  ('Ponte de glúteos unilateral','Perna','Ponte Glúteos','https://youtu.be/OGGtZdctyiY','gluteo:1|posterior_de_coxa:0.5|adutores:0.3','Livre'),
  ('Ponte glúteos barra','Perna','Ponte Glúteos','https://youtube.com/shorts/PmqFtRqgN1k?feature=share','gluteo:1|posterior_de_coxa:0.5','Barra'),
  ('Ponte glúteos máquina','Perna','Ponte Glúteos','https://youtu.be/15u0hrQHL14','gluteo:1|posterior_de_coxa:0.5','Máquina'),
  ('Ponte glúteos pés na barra','Perna','Ponte Glúteos','https://youtu.be/qYiF0ZaEL94','gluteo:1|posterior_de_coxa:0.5|adutores:0.3','Barra'),
  ('Ponte glúteos sofá','Perna','Ponte Glúteos','https://youtu.be/j6n6092Yiyk','gluteo:1|posterior_de_coxa:0.5','Livre'),
  ('rotadores externos anca solo','Perna','Rotadores anca','https://youtu.be/iC5v-1Y4OI4','gluteo:1','Livre'),
  ('Extensão antebraço','Geral','Antebraço','https://youtube.com/shorts/wvBMFyzDcy0?feature=share','','Livre'),
  ('Flexão antebraço','Geral','Antebraço','https://youtube.com/shorts/xEkDcXxKQJI?feature=share','','Livre'),
  ('Agachamento pliometrico','Geral','geral','https://youtu.be/DqX1dRstKwk','quadriceps:0.5|gluteo:0.5|gemeos:0.3','Livre'),
  ('Burpees','Geral','geral','https://youtu.be/TMNT0krfVk8','','Livre'),
  ('Sprint lateral','Geral','geral','https://youtu.be/_ywBc7HELjc','','Livre'),
  ('Aberturas declinadas halteres','Empurrar','Aberturas/peck deck/cross over',null,'peito:1|ombro_frontal:0.3','Halteres'),
  ('Aberturas deslizantes','Empurrar','Aberturas/peck deck/cross over','https://youtu.be/1RlJ1jFM4Gw','peito:1|ombro_frontal:0.5','Livre'),
  ('Aberturas em pé elastico','Empurrar','Aberturas/peck deck/cross over','https://youtu.be/esBpHmiwUcw','peito:1|ombro_frontal:0.5','Elástico'),
  ('Aberturas inclinadas cabos','Empurrar','Aberturas/peck deck/cross over',null,'peito:1|ombro_frontal:0.5','Cabos'),
  ('Aberturas inclinadas halteres','Empurrar','Aberturas/peck deck/cross over','https://youtu.be/VCixxR3wfoM','peito:1|ombro_frontal:0.5','Halteres'),
  ('Aberturas planas cabos','Empurrar','Aberturas/peck deck/cross over',null,'peito:1|ombro_frontal:0.5','Cabos'),
  ('Aberturas planas halteres','Empurrar','Aberturas/peck deck/cross over','https://youtube.com/shorts/aInMhTBVxbI?feature=share','peito:1|ombro_frontal:0.5','Halteres'),
  ('Aberturas TRX','Empurrar','Aberturas/peck deck/cross over','https://youtu.be/EVGFzPHpsyk','peito:1|ombro_frontal:0.5','TRX'),
  ('Butterfly machine','Empurrar','Aberturas/peck deck/cross over',null,'peito:1|ombro_frontal:0.5','Máquina'),
  ('Cross over unilateral','Empurrar','Aberturas/peck deck/cross over',null,'peito:1|ombro_frontal:0.5','Cabos'),
  ('Cross over centro','Empurrar','Aberturas/peck deck/cross over','https://youtu.be/iVzxWUUvuW8','peito:1|ombro_frontal:0.5','Cabos'),
  ('Cross over de baixo','Empurrar','Aberturas/peck deck/cross over','https://youtu.be/S7mRgBc8sdQ','peito:1|ombro_frontal:0.5','Cabos'),
  ('Cross over de baixo no banco','Empurrar','Aberturas/peck deck/cross over','https://youtu.be/Ryus82ZHEEU','peito:1|ombro_frontal:0.5','Cabos'),
  ('Cross over de cima','Empurrar','Aberturas/peck deck/cross over','https://youtu.be/X7nnAmvmf6Y','peito:1|ombro_frontal:0.3','Cabos'),
  ('Peck deck','Empurrar','Aberturas/peck deck/cross over','https://youtu.be/T7xL9iNgSgA','peito:1','Máquina'),
  ('Elevações frontais barra','Empurrar','Elevações frontais',null,'ombro_frontal:1|ombro_medio:0.5','Barra'),
  ('Elevações frontais halteres','Empurrar','Elevações frontais',null,'ombro_frontal:1|ombro_medio:0.5','Halteres'),
  ('Elevações frontais mochila','Empurrar','Elevações frontais','https://youtu.be/LFb5ENgNIt4','ombro_frontal:1|ombro_medio:0.5','Livre'),
  ('Elevações laterais cabos anca','Empurrar','Elevações laterais','https://youtu.be/iq2FQHFlNjs','ombro_frontal:1|ombro_posterior:1|ombro_medio:1|trapezio:0.5','Cabos'),
  ('Elevações laterais cabos baixo','Empurrar','Elevações laterais','https://youtu.be/GWGo_w4b7fU','ombro_frontal:1|ombro_posterior:1|ombro_medio:1|trapezio:0.5','Cabos'),
  ('Elevações laterais cabos joelho','Empurrar','Elevações laterais','https://youtu.be/UqW1_7atqtg','ombro_frontal:1|ombro_posterior:1|ombro_medio:1|trapezio:0.5','Cabos'),
  ('Elevações laterais cabos cross','Empurrar','Elevações laterais','https://youtu.be/2JnxTklcDvQ','ombro_frontal:1|ombro_posterior:1|ombro_medio:1|trapezio:0.5','Cabos'),
  ('Elevações laterais deitado halteres','Empurrar','Elevações laterais','https://youtu.be/r4WDya0RZxE','ombro_frontal:1|ombro_posterior:1|ombro_medio:1|trapezio:0.5','Halteres'),
  ('Elevações laterais em pé halteres','Empurrar','Elevações laterais','https://youtu.be/cndZI8LA7VI','ombro_frontal:1|ombro_posterior:1|ombro_medio:1|trapezio:0.5','Halteres'),
  ('Elevações laterais em pé inclinado halteres','Empurrar','Elevações laterais','https://youtu.be/zO7I1e7FZAE','ombro_frontal:1|ombro_posterior:1|ombro_medio:1|trapezio:0.5','Halteres'),
  ('Elevações laterais máquina','Empurrar','Elevações laterais','https://youtu.be/QNcMV949pn0','ombro_frontal:1|ombro_posterior:1|ombro_medio:1|trapezio:0.5','Máquina'),
  ('Elevações laterais sentado halteres','Empurrar','Elevações laterais','https://youtu.be/ZcR4nbHOVqk','ombro_frontal:1|ombro_posterior:1|ombro_medio:1|trapezio:0.5','Halteres'),
  ('Fundos máquina assistida','Empurrar','Fundos','https://youtube.com/shorts/YMBh0ST03RM?feature=share','triceps:1|peito:0.5|ombro_frontal:0.3','Máquina'),
  ('Fundos nas costas da cadeira','Empurrar','Fundos','https://youtu.be/VLtfSGUsVio','triceps:1|peito:1|ombro_frontal:0.3','Livre'),
  ('Fundos paralelas','Empurrar','Fundos','https://youtu.be/Vd-dZ4CScKU','triceps:1|peito:1|ombro_frontal:0.3','Livre'),
  ('Fundos máquina','Empurrar','Fundos','https://youtube.com/shorts/bhuf9kWbVtM?feature=share','triceps:1|peito:0.5|ombro_frontal:0.3','Máquina'),
  ('Fundos paralelas elástico','Empurrar','Fundos','https://youtu.be/zMfDaWFqLCo','triceps:1|peito:1|ombro_frontal:0.3','Elástico'),
  ('Fundos na cadeira','Empurrar','Fundos banco','https://youtu.be/2ZrqzTvbxRE','triceps:1|peito:0.5|ombro_frontal:0.3','Livre'),
  ('Fundos no banco','Empurrar','Fundos banco','https://youtu.be/lJHNeSpM65c','triceps:1|peito:0.5|ombro_frontal:0.3','Banco'),
  ('Fundos no banco com pés noutro banco','Empurrar','Fundos banco','https://youtu.be/xW3CK4j1TjE','triceps:1|peito:0.5|ombro_frontal:0.3','Banco'),
  ('Press arnold sentado','Empurrar','Press ombro/press arnold','https://youtu.be/utbGNed_V68','ombro_frontal:1|ombro_medio:0.5|triceps:0.3','Livre'),
  ('Press ombro máquina','Empurrar','Press ombro/press arnold','https://youtu.be/6PG79Ezhfzo','ombro_frontal:1|ombro_medio:0.5|triceps:0.5','Máquina'),
  ('Press ombro pé barra','Empurrar','Press ombro/press arnold','https://youtu.be/sNMwCdJJSt4','ombro_frontal:1|ombro_medio:0.5|triceps:0.5','Barra'),
  ('Press ombro pé halteres','Empurrar','Press ombro/press arnold',null,'ombro_frontal:1|ombro_medio:0.5|triceps:0.3','Halteres'),
  ('Press ombro pé mochila','Empurrar','Press ombro/press arnold','https://youtu.be/Zuy1CG434Tw','ombro_frontal:1|ombro_medio:0.5|triceps:0.3','Livre'),
  ('Press ombro pino','Empurrar','Press ombro/press arnold','https://youtu.be/VwvFea-fIs8','ombro_frontal:1|ombro_medio:0.5|triceps:0.5','Livre'),
  ('Press ombro sentado barra livre','Empurrar','Press ombro/press arnold','https://youtu.be/Krm1v3RP4Iw','ombro_frontal:1|ombro_medio:0.5|triceps:0.5','Barra'),
  ('Press ombro sentado halteres','Empurrar','Press ombro/press arnold','https://youtu.be/B5MFTNbu_cs','ombro_frontal:1|ombro_medio:0.5|triceps:0.5','Halteres'),
  ('Press ombro sentado smith','Empurrar','Press ombro/press arnold','https://youtu.be/T2mzHsQtjZs','ombro_frontal:1|ombro_medio:0.5|triceps:0.5','Barra'),
  ('Press ombro sentado smith pega junta','Empurrar','Press ombro/press arnold','https://youtu.be/e3ugqY_wxy8','ombro_frontal:1|ombro_medio:0.5|triceps:0.5','Barra'),
  ('Flexões','Empurrar','Supino/flexões','https://youtu.be/ZFBG6Lrfl50','peito:1|ombro_frontal:0.5|triceps:0.5','Livre'),
  ('Flexões joelhos chão','Empurrar','Supino/flexões','https://youtu.be/6BqneAOg_VI','peito:1|ombro_frontal:0.5|triceps:0.5','Livre'),
  ('Flexões mão elevadas','Empurrar','Supino/flexões','https://youtu.be/NHZrRCz48cQ','peito:1|ombro_frontal:0.5|triceps:0.5','Livre'),
  ('Flexões mão step','Empurrar','Supino/flexões','https://youtu.be/vYK58oAZv30','peito:1|ombro_frontal:0.5|triceps:0.5','Livre'),
  ('Flexões pés elevados','Empurrar','Supino/flexões','https://youtu.be/gMs8t_heBtM','peito:1|ombro_frontal:0.5|triceps:0.5','Livre'),
  ('Flexões TRX','Empurrar','Supino/flexões','https://youtu.be/d9Ay9FN0-0k','peito:1|ombro_frontal:0.5|triceps:0.5','TRX'),
  ('Press peito pé elastico','Empurrar','Supino/flexões','https://youtu.be/Hprh6T-d2KM','peito:1|ombro_frontal:0.5|triceps:0.5','Elástico'),
  ('Supino declinado barra','Empurrar','Supino/flexões','https://youtu.be/G8KYVpkCkOA','peito:1|triceps:0.5|ombro_frontal:0.3','Barra'),
  ('Supino declinado barra pega junta','Empurrar','Supino/flexões',null,'peito:1|triceps:0.5|ombro_frontal:0.3','Barra'),
  ('Supino declinado halteres','Empurrar','Supino/flexões',null,'peito:1|triceps:0.5|ombro_frontal:0.3','Halteres'),
  ('Supino inclinado barra','Empurrar','Supino/flexões','https://youtu.be/NCX6IShzOwo','peito:1|ombro_frontal:0.5|triceps:0.5','Barra'),
  ('Supino inclinado barra pega junta','Empurrar','Supino/flexões','https://youtube.com/shorts/0CL9kjbImBY?feature=share','peito:1|ombro_frontal:0.5|triceps:0.5','Barra'),
  ('Supino inclinado halteres','Empurrar','Supino/flexões','https://youtu.be/5ex6XUWB0_k','peito:1|ombro_frontal:0.5|triceps:0.5','Halteres'),
  ('Supino inclinado máquina','Empurrar','Supino/flexões','https://youtu.be/GslrzAkiYII','peito:1|ombro_frontal:0.5|triceps:0.5','Máquina'),
  ('Supino na maquina deitado','Empurrar','Supino/flexões','https://youtu.be/wEr6WQaxczU','peito:1|ombro_frontal:0.5|triceps:0.5','Máquina'),
  ('Supino plano barra','Empurrar','Supino/flexões','https://youtu.be/Xzv5or9mINw','peito:1|ombro_frontal:0.5|triceps:0.5','Barra'),
  ('Supino plano barra pega junta','Empurrar','Supino/flexões','https://youtu.be/ZyyDc4g2h6w','peito:1|ombro_frontal:0.5|triceps:0.5','Barra'),
  ('Supino plano halteres','Empurrar','Supino/flexões','https://youtu.be/zLehuYDhAJU','peito:1|ombro_frontal:0.5|triceps:0.5','Halteres'),
  ('Supino plano máquina','Empurrar','Supino/flexões','https://youtu.be/oTgcomRRaWw','peito:1|ombro_frontal:0.5|triceps:0.5','Máquina'),
  ('Triceps a testa banco inclinado halteres','Empurrar','Triceps',null,'triceps:1','Halteres'),
  ('Triceps a testa barra','Empurrar','Triceps',null,'triceps:1','Barra'),
  ('Triceps a testa halteres','Empurrar','Triceps','https://youtu.be/iN0OFn6E11I','triceps:1','Halteres'),
  ('Triceps corda pé','Empurrar','Triceps','https://youtu.be/leX1rrEioL0','triceps:1','Livre'),
  ('Triceps francês cabos','Empurrar','Triceps','https://youtu.be/4q112HC_wzo','triceps:1','Cabos'),
  ('Triceps francês cabos uniateral','Empurrar','Triceps','https://youtu.be/9EFf0IW-Fpo','triceps:1','Cabos'),
  ('Triceps francês elastico','Empurrar','Triceps','https://youtu.be/bH1yhptIOzc','triceps:1','Elástico'),
  ('Triceps francês halteres','Empurrar','Triceps','https://youtu.be/XsmOTlaKUTA','triceps:1','Halteres'),
  ('Triceps kick back cabos','Empurrar','Triceps','https://youtu.be/DxY2sbMDtK0','triceps:1','Cabos'),
  ('Triceps kick back halteres','Empurrar','Triceps',null,'triceps:1','Halteres'),
  ('Triceps máquina','Empurrar','Triceps','https://youtu.be/cVM4K_I4z18','triceps:1','Máquina'),
  ('Triceps nuca cabos','Empurrar','Triceps','https://youtu.be/5XOLZLFhzw0','triceps:1','Cabos'),
  ('Triceps nuca na mesa','Empurrar','Triceps','https://youtu.be/BCIU_SIsviM','triceps:1','Livre'),
  ('Triceps puxador','Empurrar','Triceps','https://youtu.be/OFiwrn4IUD8','triceps:1','Livre'),
  ('Triceps TRX','Empurrar','Triceps','https://youtu.be/G2WSOSw9C3M','triceps:1','TRX'),
  ('Tricpes unilateral nos cabos de costas','Empurrar','Triceps','https://youtu.be/Ujba6U2v85E','triceps:1','Cabos'),
  ('Abdominal crunch','Core','Abdominal','https://youtu.be/aEAm7bUhWYI','abs:1','Livre'),
  ('Abdominal declinado','Core','Abdominal','https://youtu.be/l4XbbB0Kgto','abs:1','Livre'),
  ('Abdominal deitado cabos','Core','Abdominal','https://youtu.be/3MlH7m1lWYo','abs:1','Cabos'),
  ('Abdominal inferior inclinado','Core','Abdominal','https://youtu.be/G_YeVq913TM','abs:1','Livre'),
  ('Abdominal inferior paralelas','Core','Abdominal','https://youtu.be/Rf89J8jpb-M','abs:1','Livre'),
  ('Abdominal inferior solo','Core','Abdominal','https://youtu.be/kJZiWK7bQzo','abs:1','Livre'),
  ('Abdominal inferior TRX','Core','Abdominal','https://youtu.be/BhJm3bsy3AQ','abs:1','TRX'),
  ('Abdominal lateral','Core','Abdominal','https://youtu.be/Ks0By-PzviA','abs:1','Livre'),
  ('Abdominal na corda','Core','Abdominal','https://youtu.be/5N8_sEkk6zU','abs:1','Livre'),
  ('Abdominal na máquina','Core','Abdominal','https://youtu.be/By7JDAyBuyY','abs:1','Máquina'),
  ('Abdominal obliquo','Core','Abdominal',null,'abs:1','Livre'),
  ('Abdominal roller','Core','Abdominal','https://youtu.be/fYpYYg7lT_Y','abs:1|dorsal:0.5','Livre'),
  ('Abdominal tesouras','Core','Abdominal','https://youtu.be/pOVTprvuTOE','abs:1','Livre'),
  ('Abdominal total','Core','Abdominal','https://youtu.be/YGoZy8Y5yms','abs:1','Livre'),
  ('Climber','Core','Abdominal','https://youtu.be/pRkHcAxP1wQ','abs:1','Livre'),
  ('Jack nife TRX','Core','Abdominal','https://youtu.be/JB0PSsIDHTw','abs:1','TRX'),
  ('Kness to bar','Core','Abdominal',null,'abs:1','Livre'),
  ('Prancha frontal 3 apoios','Core','Abdominal','https://youtu.be/tUKjmSylLIg','abs:1','Livre'),
  ('Prancha frontal dinâmica (joelho ao cotovelo)','Core','Abdominal','https://youtu.be/BNPYAPsfXe4','abs:1','Livre'),
  ('Prancha frontal solo','Core','Abdominal',null,'abs:1','Livre'),
  ('Prancha lateral dinamica','Core','Abdominal',null,'abs:1','Livre'),
  ('Pranha frontal 2 apoios','Core','Abdominal','https://youtu.be/eoPHHS0REjc','abs:1','Livre'),
  ('Remada em prancha','Core','Abdominal',null,'abs:1','Livre'),
  ('Russian twist','Core','Abdominal','https://youtu.be/4rdQ7N-u9Sc','abs:1','Livre'),
  ('Super homem','Core','Abdominal','https://youtu.be/rqSE5w3qL2o','abs:1','Livre'),
  ('Super homem 4 apoios','Core','Abdominal','https://youtu.be/VXWulXnxHOY','abs:1','Livre'),
  ('Toe to bar','Core','Abdominal','https://youtu.be/iMdpJQ6aUgM','abs:1','Livre'),
  ('V-up','Core','Abdominal',null,'abs:1','Livre'),
  ('Lombares banco','Core','Lombar','https://youtu.be/rhD38IyqgtM','lombares:1','Banco'),
  ('Lombares máquina','Core','Lombar','https://youtu.be/TTU6gfgIohU','lombares:1','Máquina'),
  ('Lombares no solo','Core','Lombar','https://youtu.be/PllczP42iXs','lombares:1','Livre')
) as d(name, pattern, category, video_url, m, equipment);
